# Generated by nativegate. Do not edit by hand — re-run `ngate test`.
# Extend with real assertions; this is a build/import smoke test.
import numpy as np


def test_pvt_set_fluid_importable():
    from petro_api import pvt_set_fluid

    pvt_set_fluid(1.0, 1.0, 1.0, 1)

def test_solution_gor_importable():
    from petro_api import solution_gor

    solution_gor(1.0)

def test_oil_fvf_importable():
    from petro_api import oil_fvf

    oil_fvf(1.0)

def test_oil_viscosity_importable():
    from petro_api import oil_viscosity

    oil_viscosity(1.0)

def test_gas_z_factor_importable():
    from petro_api import gas_z_factor

    gas_z_factor(1.0)

def test_bubble_point_importable():
    from petro_api import bubble_point

    bubble_point(1.0)

def test_pvt_state_importable():
    from petro_api import pvt_state

    pvt_state(1.0, np.array([1.0, 2.0, 3.0], dtype=np.float64), 1)

def test_tubing_bhp_importable():
    from petro_api import tubing_bhp

    tubing_bhp(1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1)

def test_vogel_rate_importable():
    from petro_api import vogel_rate

    vogel_rate(1.0, 1.0, 1.0)

def test_last_error_importable():
    from petro_api import last_error

    last_error()
