# Generated by native2py. Do not edit by hand — re-run `native2py generate`.
"""Numerical regression: the answers must not change.

`golden.json` records what every bound entry point returned for a fixed set
of inputs. This replays those calls against the currently built extension and
compares within the tolerance recorded in the file.

A failure here does not necessarily mean a bug — it means the numbers moved.
Investigate, then re-record deliberately with:

    native2py golden record petro_api

and review the diff in golden.json like any other change to behaviour.
"""

import json
import math
from pathlib import Path

import pytest

import petro_api

GOLDEN_PATH = Path(__file__).resolve().parent.parent / "golden.json"


def _materialise(value):
    if isinstance(value, dict) and "__struct__" in value:
        native = getattr(petro_api, value["__struct__"])()
        for name, field in value["fields"].items():
            setattr(native, name, _materialise(field))
        return native
    return value


def _jsonable(value):
    if value is None or isinstance(value, (bool, int, float, str)):
        return value
    if isinstance(value, (list, tuple)):
        return [_jsonable(v) for v in value]
    if hasattr(value, "tolist"):
        return _jsonable(value.tolist())
    return {
        name: _jsonable(getattr(value, name))
        for name in dir(value)
        if not name.startswith("_") and not callable(getattr(value, name))
    }


def _invoke(entry):
    arguments = [_materialise(a) for a in entry["arguments"]]
    if entry["kind"] == "function":
        target = getattr(petro_api, entry["name"])
    elif entry["kind"] == "static":
        target = getattr(getattr(petro_api, entry["class"]), entry["name"])
    else:
        cls = getattr(petro_api, entry["class"])
        instance = cls(*[_materialise(a) for a in entry["constructor_arguments"]])
        target = getattr(instance, entry["name"])
    return _jsonable(target(*arguments))


def _close(expected, actual, rtol, atol):
    if isinstance(expected, bool) or isinstance(actual, bool):
        return expected == actual
    if isinstance(expected, (int, float)) and isinstance(actual, (int, float)):
        if math.isnan(expected) and math.isnan(actual):
            return True
        return math.isclose(expected, actual, rel_tol=rtol, abs_tol=atol)
    if isinstance(expected, list) and isinstance(actual, list):
        return len(expected) == len(actual) and all(
            _close(e, a, rtol, atol) for e, a in zip(expected, actual)
        )
    if isinstance(expected, dict) and isinstance(actual, dict):
        return expected.keys() == actual.keys() and all(
            _close(expected[k], actual[k], rtol, atol) for k in expected
        )
    return expected == actual


def _document():
    if not GOLDEN_PATH.exists():
        pytest.skip(
            f"no {GOLDEN_PATH.name} recorded yet — run `native2py golden record petro_api`"
        )
    return json.loads(GOLDEN_PATH.read_text())


def test_golden_values_are_unchanged():
    document = _document()
    tolerance = document.get("tolerance") or {}
    rtol = tolerance.get("rtol", 1e-12)
    atol = tolerance.get("atol", 0.0)

    differences = []
    for key, entry in (document.get("entries") or {}).items():
        try:
            actual = _invoke(entry)
        except Exception as exc:  # noqa: BLE001
            differences.append(f"{key}: recorded, but this build cannot call it — {exc}")
            continue
        expected = entry.get("result")
        if not _close(expected, actual, rtol, atol):
            differences.append(f"{key}: expected {expected!r}, got {actual!r}")

    assert not differences, "numerical regression:\n  " + "\n  ".join(differences)


def test_golden_file_covers_the_api():
    # A golden file that records two of forty entry points passes every run
    # and proves almost nothing. This asserts only that *something* is
    # covered; the skip reasons in the file say what is not.
    document = _document()
    assert document.get("entries"), (
        "golden.json records no entry points at all — see its 'skipped' block "
        "for why, then re-record with `native2py golden record petro_api`"
    )
