"""Kubernetes manifests for a generated service (design.md sections 4, 20, 21).

`ngate init` created an empty `infrastructure/kubernetes/` and nothing
else, so every deployment was hand-written from scratch — which in practice
means the security context and the probes are whatever the person in a hurry
remembered. This generates them.

The manifests are deliberately *opinionated about safety and vague about
scale*: replica counts, CPU limits and image registries are yours, but the
security context, the probe wiring and the COMMON-block worker constraint are
not negotiable defaults, because each of them is a lesson already paid for
elsewhere in this codebase.

VALIDATION

`tests/test_k8s_gen.py` parses the output as YAML and asserts on the resulting
objects, because a substring check passes happily on a file `kubectl` rejects.
Beyond that, the generated manifests were deserialized into the official
`kubernetes` client's `V1Deployment` / `V1Service` models and round-tripped:
every field survived, so nothing here is a name the real API would silently
drop. That check is not in the suite — it would mean a dependency on the
Kubernetes client for one test — so re-run it by hand if you add a field.

WHY THE PROBES ARE SPLIT THE WAY THEY ARE

`readinessProbe` -> `/readyz` and `livenessProbe` -> `/healthz`, never the
other way and never the same endpoint for both:

* `/readyz` reports 503 while the process is draining after SIGTERM. Pointing
  a *liveness* probe at it would get a draining pod killed mid-request instead
  of drained — turning a clean rolling deploy into dropped connections.
* `/healthz` stays up during a drain. Pointing a *readiness* probe at it would
  keep sending new work to a pod that is shutting down, which is the burst of
  502s the drain exists to prevent.

WHY `readOnlyRootFilesystem` NEEDS THE emptyDir

A read-only root is worth having — it removes "write a binary and execute it"
from anything that gets code execution through the native library. But CPython
wants somewhere to write, and numerical code often wants scratch space, so
`/tmp` is mounted as an emptyDir. `PYTHONDONTWRITEBYTECODE` is set in the
image so the interpreter does not try to write `.pyc` next to the source.
"""

from __future__ import annotations

# Matched to docker_gen: Fortran is pinned to one worker because COMMON blocks
# are per-process, so a configure call and the compute that reads it must land
# in the same process. Drifting from that here would silently reintroduce the
# bug at deploy time, where it is far harder to see.
_DEFAULT_WORKERS = {"cpp": 2, "fortran": 1}

MANIFEST_FILENAME = "deployment.yaml"


def generate_k8s_manifests(
    service_name: str,
    language: str,
    image: str | None = None,
    *,
    auth: str = "none",
    replicas: int = 2,
) -> str:
    """A Deployment + Service for one generated service."""
    image = image or f"{service_name}:latest"
    workers = _DEFAULT_WORKERS.get(language, 1)

    worker_note = (
        "        # One worker per POD, not per node: COMMON blocks are\n"
        "        # per-process. Scale with replicas, never by raising this,\n"
        "        # unless the exposed routines keep no state between calls.\n"
        if language == "fortran"
        else "        # Per-request instances and no process-global state.\n"
    )

    # Only rendered for api_key services. A secretKeyRef to a Secret that does
    # not exist keeps the pod in CreateContainerConfigError, which is a
    # confusing failure to hand someone who never asked for authentication.
    auth_env = ""
    auth_note = ""
    if auth == "api_key":
        auth_env = f"""
        - name: NATIVEGATE_API_KEYS
          valueFrom:
            secretKeyRef:
              name: {service_name}-api-keys
              key: keys"""
        auth_note = f"""
#
# Generated with `api.auth: api_key`. Without keys this service will
# REFUSE-TO-START, deliberately — see docs/production-readiness.md.
# Create the Secret before deploying:
#
#   kubectl create secret generic {service_name}-api-keys \\
#     --from-literal=keys="$(openssl rand -hex 32)"
#"""

    return f"""# Generated by nativegate. Do not edit by hand — re-run `ngate k8s {service_name}`.
#
# Replicas, resource limits and the image reference are starting points; the
# securityContext and the probe wiring are not. See generators/k8s_gen.py for
# why each is shaped the way it is.{auth_note}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {service_name}
  labels:
    app: {service_name}
spec:
  replicas: {replicas}
  selector:
    matchLabels:
      app: {service_name}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      # With maxUnavailable 0 a new pod must pass its readiness probe before an
      # old one is removed, so a native extension that fails to load takes the
      # rollout down instead of the service.
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: {service_name}
    spec:
      # Long enough for gunicorn's --graceful-timeout 30 to finish in-flight
      # native calls after /readyz starts reporting 503.
      terminationGracePeriodSeconds: 45
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: {service_name}
        image: {image}
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8000
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop: ["ALL"]
        env:
{worker_note}        - name: WEB_CONCURRENCY
          value: "{workers}"
        - name: NATIVEGATE_MAX_REQUEST_BYTES
          value: "1048576"{auth_env}
        # Draining: reports 503 on SIGTERM so this pod leaves the Service's
        # endpoints BEFORE it stops accepting. Must not be pointed at /healthz.
        readinessProbe:
          httpGet:
            path: /readyz
            port: http
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 2
        # Stays up during a drain, so a draining pod is not killed mid-request.
        # Must not be pointed at /readyz.
        livenessProbe:
          httpGet:
            path: /healthz
            port: http
          periodSeconds: 15
          timeoutSeconds: 3
          failureThreshold: 3
        # A native extension can take a while to load. Without this, a slow
        # start is read as a failed start and the pod restarts forever.
        startupProbe:
          httpGet:
            path: /healthz
            port: http
          periodSeconds: 3
          failureThreshold: 30
        resources:
          requests:
            cpu: "500m"
            memory: "256Mi"
          limits:
            # No CPU limit on purpose: throttling a native numerical routine
            # mid-call inflates latency badly and CPU is already bounded by
            # WEB_CONCURRENCY. Memory IS limited, because a native leak
            # otherwise takes the node down rather than the pod.
            memory: "1Gi"
        volumeMounts:
        # readOnlyRootFilesystem needs somewhere writable: CPython wants a
        # temp dir and numerical code often wants scratch space.
        - name: tmp
          mountPath: /tmp
      volumes:
      - name: tmp
        emptyDir: {{}}
---
apiVersion: v1
kind: Service
metadata:
  name: {service_name}
  labels:
    app: {service_name}
spec:
  type: ClusterIP
  selector:
    app: {service_name}
  ports:
  - name: http
    port: 80
    targetPort: http
"""
