"""Multi-stage Dockerfile generator (design.md section 11)."""

from __future__ import annotations

_LANGUAGE_BUILD_DEPS = {
    "cpp": ["build-essential", "cmake"],
    "fortran": ["build-essential", "gfortran", "cmake"],
}

_LANGUAGE_RUNTIME_DEPS = {
    "cpp": [],
    "fortran": ["libgfortran5"],
}


def generate_dockerfile(
    service_name: str,
    language: str,
    package_name: str,
    extra_build_deps: list[str] | None = None,
    libraries: list[str] | None = None,
) -> str:
    build_deps = _LANGUAGE_BUILD_DEPS.get(language, ["build-essential", "cmake"]) + (extra_build_deps or [])
    runtime_deps = _LANGUAGE_RUNTIME_DEPS.get(language, [])
    libraries = libraries or []

    runtime_install = ""
    if runtime_deps:
        deps = " \\\n        ".join(runtime_deps)
        runtime_install = (
            "\nRUN apt-get update && \\\n"
            f"    apt-get install -y --no-install-recommends {deps} && \\\n"
            "    rm -rf /var/lib/apt/lists/*\n"
        )

    build_deps_str = " \\\n        ".join(build_deps)

    # A service that links shared libraries needs them inside the build
    # context, and they live outside its own directory — so the context has
    # to be the repo root and the paths become repo-relative. Without
    # libraries we keep the simpler service-dir context.
    if libraries:
        context_note = (
            f"# NOTE: build from the REPO ROOT, not services/{service_name}/:\n"
            f"#   docker build -f services/{service_name}/Dockerfile -t {service_name}:latest .\n"
            f"# The shared libraries under libraries/ must be in the build context.\n"
        )
        copy_lines = "\n".join(
            f"COPY libraries/{lib} ./libraries/{lib}" for lib in libraries
        )
        build_stage = f"""WORKDIR /build

{copy_lines}
COPY services/{service_name} ./services/{service_name}

WORKDIR /build/services/{service_name}

RUN pip install --no-cache-dir build

RUN pip wheel . -w /dist
"""
    else:
        context_note = (
            f"# Build from services/{service_name}/:\n"
            f"#   docker build -t {service_name}:latest .\n"
        )
        build_stage = """WORKDIR /build

COPY . .

RUN pip install --no-cache-dir build

RUN pip wheel . -w /dist
"""

    return f"""# Generated by native2py. Do not edit by hand — re-run `native2py docker {service_name}`.
{context_note}FROM python:3.12-slim AS builder

RUN apt-get update && \\
    apt-get install -y \\
        {build_deps_str} && \\
    rm -rf /var/lib/apt/lists/*

{build_stage}


FROM python:3.12-slim
{runtime_install}
WORKDIR /app

COPY --from=builder /dist /dist

RUN pip install --no-cache-dir /dist/*.whl

# design.md section 21: run as non-root.
RUN useradd --create-home --uid 1000 appuser
USER appuser

HEALTHCHECK --interval=30s --timeout=3s CMD python -c "import urllib.request; urllib.request.urlopen('http://localhost:8000/docs')" || exit 1

CMD ["uvicorn", "{package_name}.service:app", "--host", "0.0.0.0", "--port", "8000"]
"""
