"""Multi-stage Dockerfile generator (design.md section 11).

Also emits the CycloneDX SBOM for a generated service — see `generate_sbom`.
Both live here because both are about what actually ends up in the shipped
image, and both have to be reproducible to be worth anything.
"""

from __future__ import annotations

import hashlib
import json
import uuid
from pathlib import Path
from typing import Iterable, Sequence

# --- Base image pin -------------------------------------------------------
#
# WHY A DIGEST AND NOT A TAG
#   `python:3.12-slim` is a MUTABLE tag. Docker Hub re-points it at a new image
#   on every patch/security rebuild, so two builds a month apart silently get
#   different interpreters, different libc, different libgfortran — with no
#   record of the change anywhere in the build. For a product whose entire
#   claim is "the re-hosted numerics return the same answers", an unpinned base
#   is a hole straight through the middle of that claim. A digest is immutable:
#   the same digest is byte-identical forever, or the pull fails.
#
#   The digest below is a multi-arch OCI image index, so it still resolves
#   correctly on amd64 and arm64 — pinning does not cost you cross-platform
#   builds.
#
# HOW TO REFRESH IT (deliberately — this is a reviewed change, not a chore)
#   With Docker available:
#       docker pull python:3.12-slim
#       docker inspect --format='{{index .RepoDigests 0}}' python:3.12-slim
#   Without Docker, straight from the registry HTTP API:
#       TOKEN=$(curl -s "https://auth.docker.io/token\
#?service=registry.docker.io&scope=repository:library/python:pull" \
#         | python3 -c "import sys,json;print(json.load(sys.stdin)['token'])")
#       curl -sI -H "Authorization: Bearer $TOKEN" \
#         -H "Accept: application/vnd.oci.image.index.v1+json" \
#         https://registry-1.docker.io/v2/library/python/manifests/3.12-slim \
#         | grep -i docker-content-digest
#   Then update BASE_IMAGE_DIGEST, note the date, rebuild, and re-run the
#   generated service's golden-value tests before shipping the new base.
#
# Resolved 2026-08-22 from registry-1.docker.io (OCI image index) for
# python:3.12-slim.
BASE_IMAGE = "python:3.12-slim"
BASE_IMAGE_DIGEST = "sha256:2c941e860699f878900b0edc2403613c234d4b32eda3cc9fa7036991a2a63c4a"
BASE_IMAGE_REF = f"{BASE_IMAGE}@{BASE_IMAGE_DIGEST}"

_LANGUAGE_BUILD_DEPS = {
    "cpp": ["build-essential", "cmake"],
    "fortran": ["build-essential", "gfortran", "cmake"],
}

_LANGUAGE_RUNTIME_DEPS = {
    "cpp": [],
    "fortran": ["libgfortran5"],
}


def generate_dockerfile(
    service_name: str,
    language: str,
    package_name: str,
    extra_build_deps: list[str] | None = None,
    libraries: list[str] | None = None,
) -> str:
    build_deps = _LANGUAGE_BUILD_DEPS.get(language, ["build-essential", "cmake"]) + (extra_build_deps or [])
    runtime_deps = _LANGUAGE_RUNTIME_DEPS.get(language, [])
    libraries = libraries or []

    runtime_install = ""
    if runtime_deps:
        deps = " \\\n        ".join(runtime_deps)
        runtime_install = (
            "\nRUN apt-get update && \\\n"
            f"    apt-get install -y --no-install-recommends {deps} && \\\n"
            "    rm -rf /var/lib/apt/lists/*\n"
        )

    build_deps_str = " \\\n        ".join(build_deps)

    # A service that links shared libraries needs them inside the build
    # context, and they live outside its own directory — so the context has
    # to be the repo root and the paths become repo-relative. Without
    # libraries we keep the simpler service-dir context.
    if libraries:
        context_note = (
            f"# NOTE: build from the REPO ROOT, not services/{service_name}/:\n"
            f"#   docker build -f services/{service_name}/Dockerfile -t {service_name}:latest .\n"
            f"# The shared libraries under libraries/ must be in the build context.\n"
        )
        copy_lines = "\n".join(
            f"COPY libraries/{lib} ./libraries/{lib}" for lib in libraries
        )
        build_stage = f"""WORKDIR /build

{copy_lines}
COPY services/{service_name} ./services/{service_name}

WORKDIR /build/services/{service_name}

RUN pip install --no-cache-dir build

RUN pip wheel . -w /dist
"""
    else:
        context_note = (
            f"# Build from services/{service_name}/:\n"
            f"#   docker build -t {service_name}:latest .\n"
        )
        build_stage = """WORKDIR /build

COPY . .

RUN pip install --no-cache-dir build

RUN pip wheel . -w /dist
"""

    return f"""# Generated by native2py. Do not edit by hand — re-run `native2py docker {service_name}`.
{context_note}# Base image is DIGEST-PINNED, not tag-pinned — see docker_gen.BASE_IMAGE_DIGEST
# for why, and for how to refresh it.
FROM {BASE_IMAGE_REF} AS builder

RUN apt-get update && \\
    apt-get install -y \\
        {build_deps_str} && \\
    rm -rf /var/lib/apt/lists/*

{build_stage}


FROM {BASE_IMAGE_REF}
{runtime_install}
WORKDIR /app

COPY --from=builder /dist /dist

RUN pip install --no-cache-dir /dist/*.whl

# design.md section 21: run as non-root.
RUN useradd --create-home --uid 1000 appuser
USER appuser

HEALTHCHECK --interval=30s --timeout=3s CMD python -c "import urllib.request; urllib.request.urlopen('http://localhost:8000/docs')" || exit 1

CMD ["uvicorn", "{package_name}.service:app", "--host", "0.0.0.0", "--port", "8000"]
"""


# --- CycloneDX SBOM -------------------------------------------------------

SBOM_FILENAME = "sbom.cdx.json"

# CycloneDX 1.5 is the last spec revision with broad tool support (Grype,
# Trivy, Dependency-Track, the GitHub dependency graph). Bump deliberately.
CYCLONEDX_SPEC_VERSION = "1.5"

# Namespace for deriving the BOM serial number from the BOM's own content.
# CycloneDX wants a `serialNumber`, but a random UUID would make two SBOMs of
# identical inputs differ, which destroys the point of diffing them in review.
# A UUIDv5 over the content is stable AND still unique per distinct BOM.
_SERIAL_NAMESPACE = uuid.UUID("6ba7b811-9dad-11d1-80b4-00c04fd430c8")  # RFC 4122 URL ns

# Runtime Python dependencies of a generated service, mirroring
# pyproject_gen's [project.dependencies]. Kept as a local copy on purpose:
# the SBOM should record what the generated pyproject actually declares, and
# a silent drift between the two is something a reviewer should see as a diff.
_LANGUAGE_RUNTIME_PYTHON_DEPS = {
    "cpp": ["fastapi", "uvicorn"],
    "fortran": ["fastapi", "uvicorn", "numpy"],
}

# Files the SBOM treats as "native sources compiled in". A wheel wrapping a
# 1988 Fortran deck is only auditable if the deck itself is in the manifest.
_NATIVE_SOURCE_SUFFIXES = {
    ".f", ".for", ".f77", ".f90", ".f95", ".f03", ".f08", ".inc",
    ".c", ".h", ".cc", ".cpp", ".cxx", ".hh", ".hpp", ".hxx",
}


def _sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1 << 16), b""):
            digest.update(chunk)
    return digest.hexdigest()


def find_native_sources(root: Path) -> list[Path]:
    """Every native source under `root`, sorted, build output excluded.

    Sorted so the SBOM component order does not depend on filesystem
    iteration order — a directory listing is not stable across machines.
    """
    root = Path(root)
    skip = {"build", "dist", "_skbuild", ".git", "__pycache__", ".venv"}
    found = [
        path
        for path in root.rglob("*")
        if path.is_file()
        and path.suffix.lower() in _NATIVE_SOURCE_SUFFIXES
        and not any(part in skip for part in path.relative_to(root).parts)
    ]
    return sorted(found, key=lambda p: p.relative_to(root).as_posix())


def generate_sbom(
    service_name: str,
    language: str,
    package_name: str,
    *,
    version: str = "1.0.0",
    native_sources: Iterable[Path] | None = None,
    source_root: Path | None = None,
    libraries: Sequence[str] | None = None,
    python_dependencies: Sequence[str] | None = None,
) -> str:
    """A deterministic CycloneDX 1.5 SBOM (JSON) for one generated service.

    Records BOTH halves of what ships:

      * the Python dependency surface (fastapi, uvicorn, numpy), and
      * every native source compiled into the extension, each with its
        SHA-256 and its path relative to the service directory.

    The second half is the reason this exists. A wheel is an opaque binary;
    without the source digests there is no way to answer "which revision of
    the Fortran deck is inside this image?" during an audit.

    Determinism: no timestamps, no random serial number, sorted components.
    Two runs over unchanged inputs produce byte-identical output, so the SBOM
    can be committed and diffed like any other reviewed artifact.
    """
    source_root = Path(source_root) if source_root is not None else None
    if native_sources is None:
        native_sources = find_native_sources(source_root) if source_root else []
    if python_dependencies is None:
        python_dependencies = _LANGUAGE_RUNTIME_PYTHON_DEPS.get(
            language, _LANGUAGE_RUNTIME_PYTHON_DEPS["cpp"]
        )

    components: list[dict] = []

    for name in sorted(python_dependencies):
        components.append(
            {
                "type": "library",
                "bom-ref": f"pypi/{name}",
                "name": name,
                # No version: the generated pyproject.toml declares these
                # unpinned, so claiming a version here would be a lie. Resolve
                # the built image with `pip freeze`/syft to get versions, and
                # see docs/deployment-topologies.md.
                "purl": f"pkg:pypi/{name}",
                "scope": "required",
            }
        )

    for path in native_sources:
        path = Path(path)
        relative = (
            path.relative_to(source_root).as_posix()
            if source_root is not None and path.is_absolute()
            else Path(path).as_posix()
        )
        components.append(
            {
                "type": "file",
                "bom-ref": f"native-source/{relative}",
                "name": relative,
                "hashes": [{"alg": "SHA-256", "content": _sha256_file(path)}],
            }
        )

    for library in sorted(libraries or []):
        components.append(
            {
                "type": "library",
                "bom-ref": f"native-library/{library}",
                "name": library,
                "description": (
                    "Shared native library from libraries/ linked statically "
                    "into this service's extension module."
                ),
            }
        )

    document = {
        "bomFormat": "CycloneDX",
        "specVersion": CYCLONEDX_SPEC_VERSION,
        "version": 1,
        "metadata": {
            # No "timestamp" key: it would change on every run and make the
            # SBOM undiffable. CycloneDX makes it optional for exactly this.
            "tools": [{"vendor": "native2py", "name": "native2py"}],
            "component": {
                "type": "application",
                "bom-ref": f"pypi/{service_name}@{version}",
                "name": service_name,
                "version": version,
                "purl": f"pkg:pypi/{service_name}@{version}",
                "properties": [
                    {"name": "native2py:language", "value": language},
                    {"name": "native2py:package", "value": package_name},
                    {"name": "native2py:baseImage", "value": BASE_IMAGE_REF},
                ],
            },
        },
        "components": components,
    }

    # Serial number derived from the content above, so it is stable for
    # identical inputs and changes when anything in the BOM changes.
    payload = json.dumps(document, indent=2, sort_keys=True, ensure_ascii=False)
    document["serialNumber"] = "urn:uuid:" + str(
        uuid.uuid5(_SERIAL_NAMESPACE, payload)
    )

    return json.dumps(document, indent=2, ensure_ascii=False) + "\n"


def write_sbom(service_dir: Path, service_name: str, language: str, package_name: str, **kwargs) -> Path:
    """Write `sbom.cdx.json` into the service directory and return its path."""
    service_dir = Path(service_dir)
    kwargs.setdefault("source_root", service_dir)
    path = service_dir / SBOM_FILENAME
    path.write_text(generate_sbom(service_name, language, package_name, **kwargs))
    return path
