"""Composed-gateway generator: many services, one FastAPI app, one URL.

This is the in-process composition option (design.md section 23, Phase 2/3).
It trades independent scaling for operational simplicity: one image, one
deploy, one URL. The alternative — keep every service in its own image and
put an API gateway / K8s Ingress in front — is Phase 4 and needs no code
generation at all, just routing config. See docs/deployment-topologies.md.
"""

from __future__ import annotations


def generate_gateway_app(gateway_name: str, service_names: list[str]) -> str:
    imports = "\n".join(
        f"from {name}.router import router as {name}_router" for name in service_names
    )
    includes = "\n".join(
        f'app.include_router({name}_router, prefix="/{name}")' for name in service_names
    )
    listed = ", ".join(f'"{name}"' for name in service_names)

    return f'''# Generated by native2py. Do not edit by hand — re-run `native2py gateway`.
"""Composed API gateway: mounts each service's router under its own prefix.

Each mounted service is still built and versioned independently — this app
only depends on their installed wheels. Swapping to one-image-per-service
means dropping this file and routing at the ingress instead; the service
routers are unchanged either way.
"""
from fastapi import FastAPI

{imports}

app = FastAPI(title="{gateway_name}")

{includes}


@app.get("/healthz", tags=["health"])
def healthz():
    """Liveness: every mounted service's native extension imported cleanly."""
    return {{"status": "ok", "services": [{listed}]}}
'''


def generate_gateway_pyproject(gateway_name: str, package_name: str, service_names: list[str]) -> str:
    deps = ", ".join(f'"{name}"' for name in service_names)
    return f'''[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "{gateway_name}"
version = "1.0.0"
requires-python = ">=3.10"
# Each service is a normal wheel dependency — build them independently,
# publish them, and pin versions here like any other package.
dependencies = ["fastapi", "uvicorn", {deps}]

[tool.setuptools]
packages = ["{package_name}"]
'''
