"""Composed-gateway generator: many services, one FastAPI app, one URL.

This is the in-process composition option (design.md section 23, Phase 2/3).
It trades independent scaling for operational simplicity: one image, one
deploy, one URL. The alternative — keep every service in its own image and
put an API gateway / K8s Ingress in front — is Phase 4 and needs no code
generation at all, just routing config. See docs/deployment-topologies.md.
"""

from __future__ import annotations

from ..ir import is_valid_python_name
from .error_gen import ERROR_HANDLER_IMPORTS, generate_error_handler


def generate_gateway_app(
    gateway_name: str, service_names: list[str], package_name: str | None = None
) -> str:
    for name in service_names:
        # `from lambda.router import ...` is a SyntaxError, and so is any
        # service name that is not an identifier — say so here rather than
        # writing a gateway that cannot be imported.
        if not is_valid_python_name(name):
            raise ValueError(
                f"Service name '{name}' cannot be imported from a gateway: it is "
                "not a valid Python module name (a keyword, or not an identifier). "
                "Rename the service."
            )

    imports = "\n".join(
        f"from {name}.router import router as {name}_router" for name in service_names
    )
    includes = "\n".join(
        f'app.include_router({name}_router, prefix="/{name}")' for name in service_names
    )
    listed = ", ".join(f'"{name}"' for name in service_names)
    # The distribution name may be hyphenated ("platform-api"); the logger
    # and middleware need the importable spelling.
    package_name = package_name or gateway_name.replace("-", "_")
    # The mounted routers run under THIS app, so the gateway needs its own copy
    # of the handler — a handler on a service's own `service.py` app is not
    # reached in this topology. Same generator, so the two cannot drift.
    error_imports = "\n".join(ERROR_HANDLER_IMPORTS)

    return f'''# Generated by native2py. Do not edit by hand — re-run `native2py gateway`.
"""Composed API gateway: mounts each service's router under its own prefix.

Each mounted service is still built and versioned independently — this app
only depends on their installed wheels. Swapping to one-image-per-service
means dropping this file and routing at the ingress instead; the service
routers are unchanged either way.
"""
{error_imports}
from fastapi import FastAPI, Request

from .middleware import install_middleware, readiness
{imports}

app = FastAPI(title="{gateway_name}")

{includes}

# The mounted routers run under THIS app, so the gateway installs its own
# middleware and readiness probe. Its auth mode is the strictest of the
# services it mounts — composing an authenticated service into an open gateway
# would publish it unprotected.
install_middleware(app, "{package_name}")
readiness(app, "{package_name}")


@app.get("/healthz", tags=["health"])
def healthz():
    """Liveness: every mounted service's native extension imported cleanly."""
    return {{"status": "ok", "services": [{listed}]}}
{generate_error_handler(gateway_name)}'''


def generate_gateway_pyproject(gateway_name: str, package_name: str, service_names: list[str]) -> str:
    deps = ", ".join(f'"{name}"' for name in service_names)
    return f'''[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "{gateway_name}"
version = "1.0.0"
requires-python = ">=3.10"
# Each service is a normal wheel dependency — build them independently,
# publish them, and pin versions here like any other package.
dependencies = ["fastapi", "uvicorn", {deps}]

[tool.setuptools]
packages = ["{package_name}"]
'''
