"""pybind11 binding generator (design.md section 7)."""

from __future__ import annotations

from ..ir import ClassDef, ModuleIR, Parameter, StructDef

# Python type name -> the C++ spelling pybind11 needs in an init<> signature.
# Only the scalar types need translating; record types are already spelled
# with their C++ name in the IR.
_CPP_SPELLING = {
    "int": "int",
    "float": "double",
    "bool": "bool",
    "str": "std::string",
    "None": "void",
}


def _qualified(name: str, namespace: str | None) -> str:
    return f"{namespace}::{name}" if namespace else name


def _init_signature(params: list[Parameter], namespace: str | None) -> str:
    """C++ type list for `py::init<...>`.

    A constructor's argument types have to be spelled out for pybind11; the
    IR stores Python type names, so map back. `const char*` was recorded as
    `str`, and std::string binds from a Python str just as well.
    """
    return ", ".join(_CPP_SPELLING.get(p.type, _qualified(p.type, namespace)) for p in params)


def _emit_record(lines: list[str], record: ClassDef | StructDef, namespace: str | None) -> None:
    qualified = _qualified(record.name, record.namespace or namespace)
    # `py::class_<Derived, Base>` is what teaches pybind11 the relationship:
    # without it, inherited methods are missing from Python and a Base& return
    # never upcasts to the derived wrapper.
    bases = getattr(record, "bases", [])
    template_args = ", ".join(
        [qualified, *(_qualified(b, record.namespace or namespace) for b in bases)]
    )
    lines.append(f'    py::class_<{template_args}>(m, "{record.name}")')

    body: list[str] = []

    if isinstance(record, StructDef):
        # Plain data structs get a default constructor and read/write fields
        # so they can be built in Python and inspected after being returned.
        body.append("        .def(py::init<>())")
    else:
        if record.has_default_constructor:
            body.append("        .def(py::init<>())")
        for ctor in record.constructors:
            body.append(f"        .def(py::init<{_init_signature(ctor, namespace)}>())")
        for method in record.methods:
            body.append(f'        .def("{method.name}", &{qualified}::{method.name})')

    for field in record.fields:
        body.append(
            f'        .def_readwrite("{field.name}", &{qualified}::{field.name})'
        )

    if not body:
        # A record with nothing bindable still needs a terminated statement.
        lines[-1] += ";"
        return

    for i, line in enumerate(body):
        lines.append(line + (";" if i == len(body) - 1 else ""))


def _base_first(classes: list[ClassDef]) -> list[ClassDef]:
    """Order classes so every base is registered before anything derived.

    `py::class_<Derived, Base>` requires Base to already exist in the module;
    registering them in header order raises "generic_type: type Base is not
    registered" at *import* time, long after the build succeeded. Headers are
    merged alphabetically, so this is not a rare ordering — it is a coin flip.

    A cycle is impossible in valid C++ (you cannot derive from an incomplete
    type), but the walk is guarded anyway so a malformed IR cannot hang codegen.
    """
    by_name = {cls.name: cls for cls in classes}
    ordered: list[ClassDef] = []
    placed: set[str] = set()

    def place(cls: ClassDef, pending: frozenset[str]) -> None:
        if cls.name in placed or cls.name in pending:
            return
        for base in cls.bases:
            parent = by_name.get(base)
            if parent is not None:
                place(parent, pending | {cls.name})
        placed.add(cls.name)
        ordered.append(cls)

    for cls in classes:
        place(cls, frozenset())
    return ordered


def generate_bindings(module: ModuleIR, header_names: str | list[str]) -> str:
    """Emit one pybind11 module binding every exposed symbol.

    `header_names` may be several headers: a service with foo.hpp and bar.hpp
    produces ONE extension including both. A Python extension can only have a
    single PYBIND11_MODULE (one init symbol per .so), so generating one
    bindings file per header would leave all but one orphaned — which is
    exactly what used to happen, silently dropping those classes.
    """
    if isinstance(header_names, str):
        header_names = [header_names]

    module_symbol = f"{module.name}_cpp"

    lines = [
        "// Generated by native2py. Do not edit by hand — re-run `native2py generate`.",
        "#include <pybind11/pybind11.h>",
        "#include <string>",
        "",
        *[f'#include "{h}"' for h in header_names],
        "",
        "namespace py = pybind11;",
        "",
        f"PYBIND11_MODULE({module_symbol}, m) {{",
    ]

    namespace = module.classes[0].namespace if module.classes else None

    # Structs first: a method returning one can only be bound after the type
    # itself is registered with pybind11.
    for struct in module.structs:
        _emit_record(lines, struct, namespace)

    for cls in _base_first(module.classes):
        _emit_record(lines, cls, namespace)

    for func in module.functions:
        lines.append(f'    m.def("{func.name}", &{func.name});')

    lines.append("}")
    lines.append("")
    return "\n".join(lines)
