"""Generated Python package + FastAPI service layer (design.md sections 10, 12)."""

from __future__ import annotations

import dataclasses

from ..ir import FunctionDef, ModuleIR, Parameter, python_identifier


def _py(name: str) -> str:
    """The Python spelling of a native name (B4).

    Only the *Python* identifier changes. The HTTP route and the attribute
    looked up on the native extension keep the original spelling, so escaping
    a name never moves the wire contract or breaks the symbol lookup.
    """
    return python_identifier(name)


def _attr(target: str, native_name: str) -> str:
    """`target.native_name`, falling back to getattr for a Python keyword.

    `native.lambda` is a SyntaxError even though the pybind11/f2py attribute is
    genuinely called `lambda`, so the *access* has to be spelled differently
    while still naming the original attribute.
    """
    if _py(native_name) == native_name:
        return f"{target}.{native_name}"
    return f'getattr({target}, "{native_name}")'


class _EndpointNames:
    """Unique (route, function name) pairs for the endpoints of one router (A5).

    C++ overloads share a name, so two `viscosity` overloads previously emitted
    two `def viscosity(...)` and two `@router.post("/viscosity")` in one module:
    the second def shadowed the first and FastAPI dispatched the first route, so
    one overload was unreachable with no warning.

    Chosen fix: keep one endpoint per overload and disambiguate the later ones
    with a numeric suffix (`/viscosity_2`, `def viscosity_2`). Merging the
    overloads into a single endpoint with optional parameters was the
    alternative, but it cannot express two overloads that differ only in
    argument *type*, and it would silently pick an overload at request time
    based on which fields happened to be present — every overload stays
    individually addressable this way instead.
    """

    def __init__(self) -> None:
        self._used: set[str] = set()

    def take(self, native_name: str) -> tuple[str, str]:
        """Return (route path segment, Python function base name)."""
        base = _py(native_name)
        route, name = native_name, base
        counter = 1
        while name in self._used:
            counter += 1
            route, name = f"{native_name}_{counter}", f"{base}_{counter}"
        self._used.add(name)
        return route, name


def _native_module_symbol(module: ModuleIR) -> str:
    # cpp compiles one pybind11 extension named "<module>_cpp" (section 7);
    # f2py names the extension after the Fortran module directly (section 8).
    return f"{module.name}_cpp" if module.language == "cpp" else module.name


def generate_init_py(module: ModuleIR) -> str:
    module_symbol = _native_module_symbol(module)
    # Structs are re-exported alongside classes: a method returning one is
    # useless if the caller can't name the type to annotate or construct it.
    names = (
        [struct.name for struct in module.structs]
        + [cls.name for cls in module.classes]
        + [fn.name for fn in module.functions]
    )
    # __all__ lists the names this package actually binds, which are the escaped
    # Python spellings — `__all__ = ["lambda"]` would name something unimportable.
    all_list = ", ".join(f'"{_py(n)}"' for n in names)

    if module.language == "fortran" and any(fn.fortran_module for fn in module.functions):
        # Routines declared inside `module X ... end module X` come back from
        # f2py as attributes of a nested `<module_symbol>.<X>` fortran object,
        # not top-level names — re-export them so callers still get the flat
        # `from physics import calculate_pressure` design.md promises.
        #
        # Resolved per routine, not per service: a modern F90 facade over
        # fixed-form F77 decks has module-scoped and top-level routines in the
        # same build, and that is the normal shape of a migration in progress.
        # The attribute path uses the name f2py actually created (lower case,
        # original spelling); only the local binding is escaped for Python.
        rebindings = "\n".join(
            f"{_py(fn.name)} = "
            + (
                _attr(_attr("_native", fn.fortran_module), fn.name.lower())
                if fn.fortran_module
                else _attr("_native", fn.name.lower())
            )
            for fn in module.functions
        )
        return (
            "# Generated by native2py. Do not edit by hand — re-run `native2py generate`.\n"
            f"from ._native import {module_symbol} as _native\n\n"
            f"{rebindings}\n\n"
            f"__all__ = [{all_list}]\n"
        )

    if module.language == "fortran":
        # Fortran is case-insensitive and f2py always emits lowercase symbols,
        # but legacy sources (and therefore native2py.yaml) spell routines in
        # upper case. Alias so `PVTINI` in config keeps working while the
        # import targets the symbol that actually exists.
        native_names = {name: name.lower() for name in names}
    else:
        native_names = {name: name for name in names}

    # A native symbol whose own spelling is a Python keyword cannot appear in an
    # import statement at all (`from m import lambda as lambda_` is a
    # SyntaxError), so it is fetched by getattr from the module object instead.
    importable = [
        (native, _py(name))
        for name, native in native_names.items()
        if _py(native) == native
    ]
    by_getattr = [
        (native, _py(name))
        for name, native in native_names.items()
        if _py(native) != native
    ]

    lines = ["# Generated by native2py. Do not edit by hand — re-run `native2py generate`."]
    if not names:
        # `from ._native.svc import` with nothing after it is a SyntaxError.
        # The CLI already refuses an empty module, but a generator must not be
        # able to emit an unparsable file for any IR it is handed.
        lines.append("# Nothing exposed — check `expose:` in native2py.yaml.")
    elif by_getattr:
        lines.append(f"from ._native import {module_symbol} as _native")
        if importable:
            imports = ", ".join(
                f"{native} as {alias}" if native != alias else native
                for native, alias in importable
            )
            lines.append(f"from ._native.{module_symbol} import {imports}")
        for native, alias in by_getattr:
            lines.append(f'{alias} = getattr(_native, "{native}")')
    else:
        imports = ", ".join(
            f"{native} as {alias}" if native != alias else native
            for native, alias in importable
        )
        lines.append(f"from ._native.{module_symbol} import {imports}")

    lines.append("")
    lines.append(f"__all__ = [{all_list}]")
    return "\n".join(lines) + "\n"


# --- serialising native calls (COMMON-block safety) ----------------------

# Why this exists, in the generated file itself: a maintainer who deletes the
# lock to "fix throughput" reintroduces silently wrong numbers, so the reason
# has to travel with the code and not only with the docs.
NATIVE_LOCK_COMMENT = [
    "# Every native call below is serialised through this one process-wide lock.",
    "#",
    "# Fortran COMMON blocks are process-global storage, not per-call state. A",
    "# routine like PVTINI writes COMMON /FLUID/ and a later call to PVTRS,",
    "# PVTBO or PVTVIS reads it back — the header's own contract is \"CALL",
    "# PVTSET(P) THEN USE THE COMMON\". FastAPI runs synchronous `def` endpoints",
    "# in a threadpool, so without this lock two requests configuring different",
    "# fluids interleave their writes and reads in the SAME COMMON block and",
    "# each caller gets numbers computed from the other caller's fluid. Nothing",
    "# raises, nothing logs; the answers are just wrong.",
    "#",
    "# Per-request objects cannot fix this the way they fix a stateful C++ class:",
    "# COMMON is reachable from every instance because it belongs to the process.",
    "#",
    "# DO NOT REMOVE THIS TO IMPROVE THROUGHPUT. It caps native execution at one",
    "# concurrent call per process on purpose. The supported ways to go faster are",
    "# more processes, or an API reshaped so a configure+read pair is one call.",
    "#",
    "# RLock, not Lock: if one generated endpoint is ever changed to call another,",
    "# a plain Lock would deadlock the request against itself.",
]


def _serialised(body_lines: list[str]) -> list[str]:
    """Indent `body_lines` under `with _NATIVE_LOCK:`.

    Only the native call itself belongs inside the lock. Argument marshalling
    and JSON shaping touch no COMMON storage, and holding the lock across them
    would lengthen the critical section for no correctness gain.
    """
    return ["    with _NATIVE_LOCK:"] + [f"    {line}" for line in body_lines]


def _endpoint_for_function(
    fn: FunctionDef,
    call_expr: str,
    names: "_EndpointNames | None" = None,
    serialise: bool = False,
) -> list[str]:
    """One FastAPI endpoint for one native routine.

    Intent decides both halves of the signature. f2py drops `intent(out)`
    arguments from the call and returns them instead, so an endpoint that
    still accepted them would pass too many arguments; and `intent(in,out)`
    arguments are both passed and returned. Getting this wrong is how a
    Fortran routine's results end up discarded — the call succeeds and the
    answer goes nowhere.
    """
    names = names or _EndpointNames()
    route, py_name = names.take(fn.name)

    # Every parameter that becomes a Python identifier is escaped first (B4);
    # the call into the native routine is positional, so the values still land
    # on the right arguments.
    parameters = [_renamed(p, _py(p.name)) for p in fn.parameters]
    # intent(out) is supplied by Fortran, not by the caller.
    inputs = [p for p in parameters if p.intent != "out"]
    outputs = [p for p in parameters if p.intent != "in"]

    array_inputs = [p for p in inputs if p.is_array]
    scalar_inputs = [p for p in inputs if not p.is_array]

    sig_parts = [f"{p.name}: {p.type}" for p in scalar_inputs] + [
        f"{p.name}: list[{p.type}]" for p in array_inputs
    ]
    # The endpoint function shares fn.name with the imported native symbol
    # (see call_expr's alias in generate_service_py) — using fn.name here as
    # well would shadow the import and turn every call into infinite self-recursion.
    lines = [f'@router.post("/{route}")', f"def {py_name}_endpoint({', '.join(sig_parts)}):"]
    call_args = [p.name for p in inputs]

    body_lines = []
    for p in array_inputs:
        body_lines.append(f"    {p.name} = np.array({p.name}, dtype=np.float64)")

    call = f"{call_expr}({', '.join(call_args)})"

    def _as_json(param) -> str:
        return f"{param.name}.tolist()" if param.is_array else param.name

    # The call is kept separate from the return so it — and only it — can be
    # wrapped in the COMMON-block lock below.
    if fn.is_subroutine:
        if not outputs:
            call_lines = [f"    {call}"]
            return_line = '    return {"ok": True}'
        elif len(outputs) == 1:
            call_lines = [f"    {outputs[0].name} = {call}"]
            return_line = f'    return {{"{outputs[0].name}": {_as_json(outputs[0])}}}'
        else:
            targets = ", ".join(p.name for p in outputs)
            call_lines = [f"    {targets} = {call}"]
            result_expr = ", ".join(f'"{p.name}": {_as_json(p)}' for p in outputs)
            return_line = f"    return {{{result_expr}}}"
    elif outputs:
        # A FUNCTION with output arguments: f2py returns the result first,
        # then each output argument, in declaration order.
        targets = ", ".join(["result"] + [p.name for p in outputs])
        call_lines = [f"    {targets} = {call}"]
        result_expr = ", ".join(
            ['"result": result'] + [f'"{p.name}": {_as_json(p)}' for p in outputs]
        )
        return_line = f"    return {{{result_expr}}}"
    elif serialise:
        # Inlining the call into the return would put JSON shaping inside the
        # lock, so the result is named first.
        call_lines = [f"    result = {call}"]
        return_line = '    return {"result": result}'
    else:
        call_lines = []
        return_line = f'    return {{"result": {call}}}'

    if serialise and call_lines:
        call_lines = _serialised(call_lines)
    body_lines.extend(call_lines)
    body_lines.append(return_line)

    return [lines[0], lines[1], *body_lines, ""]


def generate_router_py(module: ModuleIR, service_name: str) -> str:
    """The endpoints as a mountable APIRouter, deliberately WITHOUT a prefix.

    Keeping the prefix out of the router is what lets one generated service
    serve two deployment topologies from identical code: standalone (its own
    image, its own FastAPI app, paths at `/circle_area`) and composed (many
    services mounted into one gateway app under `/demo/circle_area`). The
    mounting side chooses the prefix — see generators/gateway_gen.py.

    Three rules here exist because breaking them produced services that
    *imported* wrongly rather than failing a build:

    * an instance is created **inside** each endpoint, not at module scope.
      A module-scope `sim = Simulator()` is one shared mutable object for
      every concurrent request, and for a class with no default constructor
      it is a TypeError at import — the service never starts;
    * a struct crossing the boundary is converted through a Pydantic model.
      Returning the pybind11 object gets a 500 from the JSON encoder at
      request time, with the class bound perfectly well underneath;
    * a signature native2py cannot serialise (a bound *class* as a parameter
      or return) gets no endpoint and a comment saying why, because FastAPI
      raises on an unknown annotation when the router is registered — again,
      at import.
    """
    structs = {struct.name: struct for struct in module.structs}
    class_names = {cls.name for cls in module.classes}

    needs_numpy = any(p.is_array for fn in module.functions for p in fn.parameters)

    # Fortran only. A C++ service already builds a fresh instance per request
    # (see below), and a C++ free function has no equivalent of COMMON unless
    # it uses file-scope statics — which the parser cannot see, so a lock there
    # would be a guess that costs every C++ service its concurrency.
    serialise = module.language == "fortran"

    lines = [
        "# Generated by native2py. Do not edit by hand — re-run `native2py generate`.",
    ]
    if serialise:
        lines.append("import threading")
    if needs_numpy:
        lines.append("import numpy as np")
    lines.append("from fastapi import APIRouter")
    if structs:
        lines.append("from pydantic import BaseModel")
    lines.append("")

    # The package re-exports every symbol under its escaped Python name (B4),
    # so that is what the router imports.
    imported_names = [
        _py(name)
        for name in (
            [struct.name for struct in module.structs]
            + [cls.name for cls in module.classes]
            + [fn.name for fn in module.functions]
        )
    ]
    if imported_names:
        lines.append(f"from . import {', '.join(imported_names)}")
    lines.append("")

    lines.extend(_struct_models(module, structs))

    if serialise:
        lines.extend(NATIVE_LOCK_COMMENT)
        lines.append("_NATIVE_LOCK = threading.RLock()")
        lines.append("")

    lines.append(f'router = APIRouter(tags=["{service_name}"])')
    lines.append("")

    # One registry for the whole file: a class method and a free function can
    # collide just as two overloads of one method can (A5).
    names = _EndpointNames()

    for cls in module.classes:
        lines.extend(
            _endpoints_for_class(cls, structs, class_names, names, serialise=serialise)
        )

    for fn in module.functions:
        if module.language == "cpp":
            lines.extend(_endpoint_for_cpp_function(fn, structs, class_names, names))
        else:
            lines.extend(
                _endpoint_for_function(fn, _py(fn.name), names, serialise=serialise)
            )

    return "\n".join(lines).rstrip() + "\n"


# --- structs over HTTP ---------------------------------------------------


def _model_name(struct_name: str) -> str:
    return f"{_py(struct_name)}Model"


def _struct_models(module: ModuleIR, structs: dict) -> list[str]:
    """A Pydantic model, a parser and a serialiser for each bound struct.

    pybind11 hands Python a real C++ object; FastAPI needs something it can
    encode. The conversions are explicit rather than a generic `__dict__`
    walk so a field the IR never bound cannot silently appear in an API
    response.
    """
    lines: list[str] = []
    for struct in module.structs:
        lines.append(f"class {_model_name(struct.name)}(BaseModel):")
        if not struct.fields:
            lines.append("    pass")
        for field in struct.fields:
            # A field whose native name is a Python keyword is escaped on both
            # sides of the boundary — the model attribute AND the JSON key — so
            # a request body round-trips through the response unchanged. The
            # native member is still reached under its original spelling below.
            lines.append(f"    {_py(field.name)}: {_annotation(field, structs)}")
        lines.append("")
        lines.append("")

    for struct in module.structs:
        # native -> JSON
        lines.append(f"def _from_{_py(struct.name)}(native) -> dict:")
        if not struct.fields:
            lines.append("    return {}")
        else:
            items = ", ".join(
                f'"{_py(f.name)}": {_field_to_json(f, structs)}' for f in struct.fields
            )
            lines.append(f"    return {{{items}}}")
        lines.append("")
        lines.append("")

        # JSON -> native
        lines.append(f"def _to_{_py(struct.name)}(model: {_model_name(struct.name)}):")
        lines.append(f"    native = {_py(struct.name)}()")
        for field in struct.fields:
            value = _field_to_native(field, structs)
            if _py(field.name) == field.name:
                lines.append(f"    native.{field.name} = {value}")
            else:
                lines.append(f'    setattr(native, "{field.name}", {value})')
        lines.append("    return native")
        lines.append("")
        lines.append("")

    return lines


def _annotation(param, structs: dict) -> str:
    """The Python type annotation FastAPI should see for one parameter/field."""
    base = _model_name(param.type) if param.type in structs else param.type
    return f"list[{base}]" if param.is_array else base


def _field_to_json(field, structs: dict) -> str:
    access = _attr("native", field.name)
    if field.type in structs:
        return (
            f"[_from_{_py(field.type)}(v) for v in {access}]"
            if field.is_array
            else f"_from_{_py(field.type)}({access})"
        )
    return f"list({access})" if field.is_array else access


def _field_to_native(field, structs: dict) -> str:
    access = f"model.{_py(field.name)}"
    if field.type in structs:
        return (
            f"[_to_{_py(field.type)}(v) for v in {access}]"
            if field.is_array
            else f"_to_{_py(field.type)}({access})"
        )
    return access


def _unserialisable(params, returns: str, structs: dict, class_names: set) -> str | None:
    """Why this signature cannot be exposed over HTTP, or None if it can.

    A bound class is a live C++ object: there is no JSON that constructs one
    and none that represents one. It stays available in the Python package —
    only the HTTP endpoint is impossible.
    """
    for param in params:
        if param.type in class_names and param.type not in structs:
            return f"parameter '{param.name}' is a bound class ({param.type})"
    if returns in class_names and returns not in structs:
        return f"it returns a bound class ({returns})"
    return None


def _call_arguments(params, structs: dict) -> list[str]:
    return [
        f"_to_{_py(p.type)}({p.name})"
        if p.type in structs and not p.is_array
        else p.name
        for p in params
    ]


def _wrap_result(expression: str, returns: str, structs: dict) -> str:
    if returns in structs:
        return f"_from_{_py(returns)}({expression})"
    return expression


# --- class endpoints -----------------------------------------------------


def _constructor_parameters(cls) -> list | None:
    """The constructor arguments an endpoint must accept, or None if the class
    cannot be constructed from a request at all.

    A default constructor needs nothing. Otherwise the shortest public
    constructor is used — it asks the caller for the least, and every
    constructor of a class builds the same type.
    """
    if cls.has_default_constructor:
        return []
    if not cls.constructors:
        return None
    return min(cls.constructors, key=len)


def _endpoints_for_class(
    cls,
    structs: dict,
    class_names: set,
    names: "_EndpointNames | None" = None,
    serialise: bool = False,
) -> list[str]:
    names = names or _EndpointNames()
    lines: list[str] = []
    ctor_params = _constructor_parameters(cls)

    if ctor_params is None and any(not m.is_static for m in cls.methods):
        lines.append(
            f"# {cls.name}: no public constructor callable from Python "
            "(abstract, or all constructors are non-public), so its instance "
            "methods have no endpoint. It is still exported by the package and "
            "usable as a base class."
        )
        lines.append("")

    for method in cls.methods:
        if method.is_static:
            needed_ctor = []
        elif ctor_params is None:
            continue
        else:
            needed_ctor = ctor_params

        reason = _unserialisable(
            [*needed_ctor, *method.parameters], method.returns, structs, class_names
        )
        if reason is not None:
            lines.append(f"# {cls.name}.{method.name}: no endpoint — {reason}.")
            lines.append("")
            continue

        # A constructor argument sharing a name with a method argument would
        # be one parameter in the signature and the wrong value in one of the
        # two calls, so the constructor's copy is renamed. Every name is also
        # escaped against Python's keywords (B4).
        method_params = [_renamed(p, _py(p.name)) for p in method.parameters]
        method_names = {p.name for p in method_params}
        ctor_names = [
            f"{_py(p.name)}_init" if _py(p.name) in method_names else _py(p.name)
            for p in needed_ctor
        ]

        signature = [
            f"{name}: {_annotation(p, structs)}"
            for name, p in zip(ctor_names, needed_ctor)
        ] + [f"{p.name}: {_annotation(p, structs)}" for p in method_params]

        ctor_args = _call_arguments(
            [_renamed(p, name) for name, p in zip(ctor_names, needed_ctor)], structs
        )
        call_args = _call_arguments(method_params, structs)

        route, py_name = names.take(method.name)
        lines.append(f'@router.post("/{route}")')
        lines.append(f"def {py_name}({', '.join(signature)}):")
        body: list[str] = []
        if method.is_static:
            call = f"{_attr(_py(cls.name), method.name)}({', '.join(call_args)})"
        else:
            # Per request, not per process: a native class with internal state
            # shared across concurrent requests is a correctness bug, and a
            # simulation object is stateful by definition.
            body.append(f"    instance = {_py(cls.name)}({', '.join(ctor_args)})")
            call = f"{_attr('instance', method.name)}({', '.join(call_args)})"
        if method.returns == "None":
            body.append(f"    {call}")
            lines.extend(_serialised(body) if serialise else body)
            lines.append('    return {"ok": True}')
        elif serialise:
            body.append(f"    result = {call}")
            lines.extend(_serialised(body))
            lines.append(f'    return {{"result": {_wrap_result("result", method.returns, structs)}}}')
        else:
            lines.extend(body)
            lines.append(
                f'    return {{"result": {_wrap_result(call, method.returns, structs)}}}'
            )
        lines.append("")

    return lines


def _renamed(param, name: str):
    """Copy of a Parameter under a different endpoint-level name."""
    if not isinstance(param, Parameter):  # pragma: no cover - defensive
        return Parameter(
            name=name, type=param.type, is_array=param.is_array, intent=param.intent
        )
    return dataclasses.replace(param, name=name)


def _endpoint_for_cpp_function(
    fn, structs: dict, class_names: set, names: "_EndpointNames | None" = None
) -> list[str]:
    names = names or _EndpointNames()
    reason = _unserialisable(fn.parameters, fn.returns, structs, class_names)
    if reason is not None:
        return [f"# {fn.name}: no endpoint — {reason}.", ""]

    parameters = [_renamed(p, _py(p.name)) for p in fn.parameters]
    signature = ", ".join(f"{p.name}: {_annotation(p, structs)}" for p in parameters)
    call = f"{_py(fn.name)}({', '.join(_call_arguments(parameters, structs))})"

    route, py_name = names.take(fn.name)
    lines = [f'@router.post("/{route}")', f"def {py_name}_endpoint({signature}):"]
    if fn.returns == "None":
        lines.append(f"    {call}")
        lines.append('    return {"ok": True}')
    else:
        lines.append(f'    return {{"result": {_wrap_result(call, fn.returns, structs)}}}')
    lines.append("")
    return lines


def generate_service_py(service_name: str) -> str:
    """Standalone app: this service alone, in its own container.

    Thin by design — all the endpoints live in router.py so the exact same
    code can instead be mounted into a shared gateway.
    """
    return f'''# Generated by native2py. Do not edit by hand — re-run `native2py generate`.
from fastapi import FastAPI

from .router import router

app = FastAPI(title="{service_name}")
app.include_router(router)


@app.get("/healthz", tags=["health"])
def healthz():
    """Liveness: the process is up and the native extension imported."""
    return {{"status": "ok", "service": "{service_name}"}}
'''
