"""Generated Python package + FastAPI service layer (design.md sections 10, 12)."""

from __future__ import annotations

from ..ir import FunctionDef, ModuleIR, Parameter


def _native_module_symbol(module: ModuleIR) -> str:
    # cpp compiles one pybind11 extension named "<module>_cpp" (section 7);
    # f2py names the extension after the Fortran module directly (section 8).
    return f"{module.name}_cpp" if module.language == "cpp" else module.name


def generate_init_py(module: ModuleIR) -> str:
    module_symbol = _native_module_symbol(module)
    # Structs are re-exported alongside classes: a method returning one is
    # useless if the caller can't name the type to annotate or construct it.
    names = (
        [struct.name for struct in module.structs]
        + [cls.name for cls in module.classes]
        + [fn.name for fn in module.functions]
    )
    all_list = ", ".join(f'"{n}"' for n in names)

    if module.language == "fortran" and any(fn.fortran_module for fn in module.functions):
        # Routines declared inside `module X ... end module X` come back from
        # f2py as attributes of a nested `<module_symbol>.<X>` fortran object,
        # not top-level names — re-export them so callers still get the flat
        # `from physics import calculate_pressure` design.md promises.
        #
        # Resolved per routine, not per service: a modern F90 facade over
        # fixed-form F77 decks has module-scoped and top-level routines in the
        # same build, and that is the normal shape of a migration in progress.
        rebindings = "\n".join(
            f"{fn.name} = _native.{fn.fortran_module}.{fn.name.lower()}"
            if fn.fortran_module
            else f"{fn.name} = _native.{fn.name.lower()}"
            for fn in module.functions
        )
        return (
            "# Generated by native2py. Do not edit by hand — re-run `native2py generate`.\n"
            f"from ._native import {module_symbol} as _native\n\n"
            f"{rebindings}\n\n"
            f"__all__ = [{all_list}]\n"
        )

    if module.language == "fortran":
        # Fortran is case-insensitive and f2py always emits lowercase symbols,
        # but legacy sources (and therefore native2py.yaml) spell routines in
        # upper case. Alias so `PVTINI` in config keeps working while the
        # import targets the symbol that actually exists.
        imports = ", ".join(
            f"{name.lower()} as {name}" if name != name.lower() else name
            for name in names
        )
    else:
        imports = ", ".join(names)

    return (
        "# Generated by native2py. Do not edit by hand — re-run `native2py generate`.\n"
        f"from ._native.{module_symbol} import {imports}\n\n"
        f"__all__ = [{all_list}]\n"
    )


def _endpoint_for_function(fn: FunctionDef, call_expr: str) -> list[str]:
    """One FastAPI endpoint for one native routine.

    Intent decides both halves of the signature. f2py drops `intent(out)`
    arguments from the call and returns them instead, so an endpoint that
    still accepted them would pass too many arguments; and `intent(in,out)`
    arguments are both passed and returned. Getting this wrong is how a
    Fortran routine's results end up discarded — the call succeeds and the
    answer goes nowhere.
    """
    # intent(out) is supplied by Fortran, not by the caller.
    inputs = [p for p in fn.parameters if p.intent != "out"]
    outputs = [p for p in fn.parameters if p.intent != "in"]

    array_inputs = [p for p in inputs if p.is_array]
    scalar_inputs = [p for p in inputs if not p.is_array]

    sig_parts = [f"{p.name}: {p.type}" for p in scalar_inputs] + [
        f"{p.name}: list[{p.type}]" for p in array_inputs
    ]
    # The endpoint function shares fn.name with the imported native symbol
    # (see call_expr's alias in generate_service_py) — using fn.name here as
    # well would shadow the import and turn every call into infinite self-recursion.
    lines = [f'@router.post("/{fn.name}")', f"def {fn.name}_endpoint({', '.join(sig_parts)}):"]
    call_args = [p.name for p in inputs]

    body_lines = []
    for p in array_inputs:
        body_lines.append(f"    {p.name} = np.array({p.name}, dtype=np.float64)")

    call = f"{call_expr}({', '.join(call_args)})"

    def _as_json(param) -> str:
        return f"{param.name}.tolist()" if param.is_array else param.name

    if fn.is_subroutine:
        if not outputs:
            body_lines.append(f"    {call}")
            body_lines.append('    return {"ok": True}')
        elif len(outputs) == 1:
            body_lines.append(f"    {outputs[0].name} = {call}")
            body_lines.append(f'    return {{"{outputs[0].name}": {_as_json(outputs[0])}}}')
        else:
            targets = ", ".join(p.name for p in outputs)
            body_lines.append(f"    {targets} = {call}")
            result_expr = ", ".join(f'"{p.name}": {_as_json(p)}' for p in outputs)
            body_lines.append(f"    return {{{result_expr}}}")
    elif outputs:
        # A FUNCTION with output arguments: f2py returns the result first,
        # then each output argument, in declaration order.
        targets = ", ".join(["result"] + [p.name for p in outputs])
        body_lines.append(f"    {targets} = {call}")
        result_expr = ", ".join(
            ['"result": result'] + [f'"{p.name}": {_as_json(p)}' for p in outputs]
        )
        body_lines.append(f"    return {{{result_expr}}}")
    else:
        body_lines.append(f'    return {{"result": {call}}}')

    return [lines[0], lines[1], *body_lines, ""]


def generate_router_py(module: ModuleIR, service_name: str) -> str:
    """The endpoints as a mountable APIRouter, deliberately WITHOUT a prefix.

    Keeping the prefix out of the router is what lets one generated service
    serve two deployment topologies from identical code: standalone (its own
    image, its own FastAPI app, paths at `/circle_area`) and composed (many
    services mounted into one gateway app under `/demo/circle_area`). The
    mounting side chooses the prefix — see generators/gateway_gen.py.

    Three rules here exist because breaking them produced services that
    *imported* wrongly rather than failing a build:

    * an instance is created **inside** each endpoint, not at module scope.
      A module-scope `sim = Simulator()` is one shared mutable object for
      every concurrent request, and for a class with no default constructor
      it is a TypeError at import — the service never starts;
    * a struct crossing the boundary is converted through a Pydantic model.
      Returning the pybind11 object gets a 500 from the JSON encoder at
      request time, with the class bound perfectly well underneath;
    * a signature native2py cannot serialise (a bound *class* as a parameter
      or return) gets no endpoint and a comment saying why, because FastAPI
      raises on an unknown annotation when the router is registered — again,
      at import.
    """
    structs = {struct.name: struct for struct in module.structs}
    class_names = {cls.name for cls in module.classes}

    needs_numpy = any(p.is_array for fn in module.functions for p in fn.parameters)

    lines = [
        "# Generated by native2py. Do not edit by hand — re-run `native2py generate`.",
    ]
    if needs_numpy:
        lines.append("import numpy as np")
    lines.append("from fastapi import APIRouter")
    if structs:
        lines.append("from pydantic import BaseModel")
    lines.append("")

    imported_names = (
        [struct.name for struct in module.structs]
        + [cls.name for cls in module.classes]
        + [fn.name for fn in module.functions]
    )
    if imported_names:
        lines.append(f"from . import {', '.join(imported_names)}")
    lines.append("")

    lines.extend(_struct_models(module, structs))

    lines.append(f'router = APIRouter(tags=["{service_name}"])')
    lines.append("")

    for cls in module.classes:
        lines.extend(_endpoints_for_class(cls, structs, class_names))

    for fn in module.functions:
        if module.language == "cpp":
            lines.extend(_endpoint_for_cpp_function(fn, structs, class_names))
        else:
            lines.extend(_endpoint_for_function(fn, fn.name))

    return "\n".join(lines).rstrip() + "\n"


# --- structs over HTTP ---------------------------------------------------


def _model_name(struct_name: str) -> str:
    return f"{struct_name}Model"


def _struct_models(module: ModuleIR, structs: dict) -> list[str]:
    """A Pydantic model, a parser and a serialiser for each bound struct.

    pybind11 hands Python a real C++ object; FastAPI needs something it can
    encode. The conversions are explicit rather than a generic `__dict__`
    walk so a field the IR never bound cannot silently appear in an API
    response.
    """
    lines: list[str] = []
    for struct in module.structs:
        lines.append(f"class {_model_name(struct.name)}(BaseModel):")
        if not struct.fields:
            lines.append("    pass")
        for field in struct.fields:
            lines.append(f"    {field.name}: {_annotation(field, structs)}")
        lines.append("")
        lines.append("")

    for struct in module.structs:
        # native -> JSON
        lines.append(f"def _from_{struct.name}(native) -> dict:")
        if not struct.fields:
            lines.append("    return {}")
        else:
            items = ", ".join(
                f'"{f.name}": {_field_to_json(f, structs)}' for f in struct.fields
            )
            lines.append(f"    return {{{items}}}")
        lines.append("")
        lines.append("")

        # JSON -> native
        lines.append(f"def _to_{struct.name}(model: {_model_name(struct.name)}):")
        lines.append(f"    native = {struct.name}()")
        for field in struct.fields:
            lines.append(f"    native.{field.name} = {_field_to_native(field, structs)}")
        lines.append("    return native")
        lines.append("")
        lines.append("")

    return lines


def _annotation(param, structs: dict) -> str:
    """The Python type annotation FastAPI should see for one parameter/field."""
    base = _model_name(param.type) if param.type in structs else param.type
    return f"list[{base}]" if param.is_array else base


def _field_to_json(field, structs: dict) -> str:
    if field.type in structs:
        return (
            f"[_from_{field.type}(v) for v in native.{field.name}]"
            if field.is_array
            else f"_from_{field.type}(native.{field.name})"
        )
    return f"list(native.{field.name})" if field.is_array else f"native.{field.name}"


def _field_to_native(field, structs: dict) -> str:
    if field.type in structs:
        return (
            f"[_to_{field.type}(v) for v in model.{field.name}]"
            if field.is_array
            else f"_to_{field.type}(model.{field.name})"
        )
    return f"model.{field.name}"


def _unserialisable(params, returns: str, structs: dict, class_names: set) -> str | None:
    """Why this signature cannot be exposed over HTTP, or None if it can.

    A bound class is a live C++ object: there is no JSON that constructs one
    and none that represents one. It stays available in the Python package —
    only the HTTP endpoint is impossible.
    """
    for param in params:
        if param.type in class_names and param.type not in structs:
            return f"parameter '{param.name}' is a bound class ({param.type})"
    if returns in class_names and returns not in structs:
        return f"it returns a bound class ({returns})"
    return None


def _call_arguments(params, structs: dict) -> list[str]:
    return [
        f"_to_{p.type}({p.name})" if p.type in structs and not p.is_array else p.name
        for p in params
    ]


def _wrap_result(expression: str, returns: str, structs: dict) -> str:
    if returns in structs:
        return f"_from_{returns}({expression})"
    return expression


# --- class endpoints -----------------------------------------------------


def _constructor_parameters(cls) -> list | None:
    """The constructor arguments an endpoint must accept, or None if the class
    cannot be constructed from a request at all.

    A default constructor needs nothing. Otherwise the shortest public
    constructor is used — it asks the caller for the least, and every
    constructor of a class builds the same type.
    """
    if cls.has_default_constructor:
        return []
    if not cls.constructors:
        return None
    return min(cls.constructors, key=len)


def _endpoints_for_class(cls, structs: dict, class_names: set) -> list[str]:
    lines: list[str] = []
    ctor_params = _constructor_parameters(cls)

    if ctor_params is None and any(not m.is_static for m in cls.methods):
        lines.append(
            f"# {cls.name}: no public constructor callable from Python "
            "(abstract, or all constructors are non-public), so its instance "
            "methods have no endpoint. It is still exported by the package and "
            "usable as a base class."
        )
        lines.append("")

    for method in cls.methods:
        if method.is_static:
            needed_ctor = []
        elif ctor_params is None:
            continue
        else:
            needed_ctor = ctor_params

        reason = _unserialisable(
            [*needed_ctor, *method.parameters], method.returns, structs, class_names
        )
        if reason is not None:
            lines.append(f"# {cls.name}.{method.name}: no endpoint — {reason}.")
            lines.append("")
            continue

        # A constructor argument sharing a name with a method argument would
        # be one parameter in the signature and the wrong value in one of the
        # two calls, so the constructor's copy is renamed.
        method_names = {p.name for p in method.parameters}
        ctor_names = [
            f"{p.name}_init" if p.name in method_names else p.name for p in needed_ctor
        ]

        signature = [
            f"{name}: {_annotation(p, structs)}"
            for name, p in zip(ctor_names, needed_ctor)
        ] + [f"{p.name}: {_annotation(p, structs)}" for p in method.parameters]

        ctor_args = _call_arguments(
            [_renamed(p, name) for name, p in zip(ctor_names, needed_ctor)], structs
        )
        call_args = _call_arguments(method.parameters, structs)

        lines.append(f'@router.post("/{method.name}")')
        lines.append(f"def {method.name}({', '.join(signature)}):")
        if method.is_static:
            call = f"{cls.name}.{method.name}({', '.join(call_args)})"
        else:
            # Per request, not per process: a native class with internal state
            # shared across concurrent requests is a correctness bug, and a
            # simulation object is stateful by definition.
            lines.append(f"    instance = {cls.name}({', '.join(ctor_args)})")
            call = f"instance.{method.name}({', '.join(call_args)})"
        result = _wrap_result(call, method.returns, structs)
        if method.returns == "None":
            lines.append(f"    {call}")
            lines.append('    return {"ok": True}')
        else:
            lines.append(f'    return {{"result": {result}}}')
        lines.append("")

    return lines


def _renamed(param, name: str):
    """Copy of a Parameter under a different endpoint-level name."""
    return Parameter(name=name, type=param.type, is_array=param.is_array, intent=param.intent)


def _endpoint_for_cpp_function(fn, structs: dict, class_names: set) -> list[str]:
    reason = _unserialisable(fn.parameters, fn.returns, structs, class_names)
    if reason is not None:
        return [f"# {fn.name}: no endpoint — {reason}.", ""]

    signature = ", ".join(f"{p.name}: {_annotation(p, structs)}" for p in fn.parameters)
    call = f"{fn.name}({', '.join(_call_arguments(fn.parameters, structs))})"

    lines = [f'@router.post("/{fn.name}")', f"def {fn.name}_endpoint({signature}):"]
    if fn.returns == "None":
        lines.append(f"    {call}")
        lines.append('    return {"ok": True}')
    else:
        lines.append(f'    return {{"result": {_wrap_result(call, fn.returns, structs)}}}')
    lines.append("")
    return lines


def generate_service_py(service_name: str) -> str:
    """Standalone app: this service alone, in its own container.

    Thin by design — all the endpoints live in router.py so the exact same
    code can instead be mounted into a shared gateway.
    """
    return f'''# Generated by native2py. Do not edit by hand — re-run `native2py generate`.
from fastapi import FastAPI

from .router import router

app = FastAPI(title="{service_name}")
app.include_router(router)


@app.get("/healthz", tags=["health"])
def healthz():
    """Liveness: the process is up and the native extension imported."""
    return {{"status": "ok", "service": "{service_name}"}}
'''
