"""Generated pytest smoke tests (design.md section 18)."""

from __future__ import annotations

from ..ir import ModuleIR

_DEFAULT_SCALARS = {"float": "1.0", "int": "1", "bool": "True", "str": '"x"'}


def _sample_arg(param, structs: dict | None = None, classes: dict | None = None) -> str | None:
    """A literal for one argument, or None if no literal can stand in for it.

    A bound *class* parameter needs a real object; if that class cannot be
    constructed from Python either, there is nothing to pass and the caller
    drops the call rather than passing a float and failing with a TypeError.
    """
    structs = structs or {}
    classes = classes or {}
    if param.type in classes:
        cls = classes[param.type]
        args = _constructor_args(cls, structs, classes)
        return None if args is None else f"{param.type}({args})"
    if param.type in structs:
        # A struct argument needs a real instance: pybind11 binds structs with
        # a default constructor and read/write fields, so building one here
        # also proves that binding works.
        return f"{param.type}()"
    if param.is_array:
        return "np.array([1.0, 2.0, 3.0], dtype=np.float64)"
    return _DEFAULT_SCALARS.get(param.type, "1.0")


def _sample_args(params, structs: dict | None = None, classes: dict | None = None) -> str | None:
    values = [_sample_arg(p, structs, classes) for p in params]
    if any(v is None for v in values):
        return None
    return ", ".join(values)


def _constructor_args(cls, structs: dict, classes: dict | None = None) -> str | None:
    """Arguments for constructing this class in a smoke test, or None if it
    cannot be constructed from Python at all (abstract, or no public
    constructor). The shortest constructor is used — it asks for the least."""
    if cls.has_default_constructor:
        return ""
    if not cls.constructors:
        return None
    return _sample_args(min(cls.constructors, key=len), structs, classes)


def _named_types(params, structs: dict, classes: dict) -> list[str]:
    """Struct/class names appearing in a signature — every one needs importing
    into the generated test, or the sample argument is a NameError."""
    return sorted({p.type for p in params if p.type in structs or p.type in classes})


def _referenced_types(cls, structs: dict, classes: dict) -> list[str]:
    """Types the smoke test for `cls` will name, transitively.

    A class parameter is constructed inline, so its own constructor arguments
    can drag in further types.
    """
    seen: set[str] = set()
    pending = [
        p
        for m in cls.methods
        for p in m.parameters
    ] + [p for ctor in cls.constructors for p in ctor]

    while pending:
        param = pending.pop()
        if param.type in seen or param.type == cls.name:
            continue
        if param.type in structs:
            seen.add(param.type)
            pending.extend(structs[param.type].fields)
        elif param.type in classes:
            seen.add(param.type)
            nested = classes[param.type]
            if nested.constructors:
                pending.extend(min(nested.constructors, key=len))
    return sorted(seen)


def generate_python_api_test(module: ModuleIR, package_name: str) -> str:
    needs_numpy = any(p.is_array for fn in module.functions for p in fn.parameters)

    lines = [
        "# Generated by native2py. Do not edit by hand — re-run `native2py test`.",
        "# Extend with real assertions; this is a build/import smoke test.",
        "",
    ]
    if needs_numpy:
        lines.insert(2, "import numpy as np\n")

    structs = {struct.name: struct for struct in module.structs}
    classes = {cls.name: cls for cls in module.classes}

    for cls in module.classes:
        imported = ", ".join([cls.name, *_referenced_types(cls, structs, classes)])
        lines.append(f"def test_{cls.name.lower()}_importable():")
        lines.append(f"    from {package_name} import {imported}")
        lines.append("")

        constructible = _constructor_args(cls, structs, classes)
        if constructible is None:
            # An abstract class, or one whose only constructors are private:
            # `instance = Cls()` here fails the generated test suite on a
            # class that is bound correctly and usable as a base.
            lines.append(f"    assert {cls.name} is not None")
            for method in (m for m in cls.methods if m.is_static):
                args = _sample_args(method.parameters, structs, classes)
                if args is None:
                    continue
                lines.append(f"    {cls.name}.{method.name}({args})")
            lines.append("")
            continue

        lines.append(f"    instance = {cls.name}({constructible})")
        for method in cls.methods:
            args = _sample_args(method.parameters, structs, classes)
            if args is None:
                # No literal can stand in for one of the arguments; calling it
                # here would fail the generated suite on a correct binding.
                lines.append(
                    f"    # {method.name}: needs an argument this smoke test "
                    "cannot construct"
                )
                continue
            target = cls.name if method.is_static else "instance"
            lines.append(f"    {target}.{method.name}({args})")
        lines.append("")

    for func in module.functions:
        args = _sample_args(func.parameters, structs, classes)
        if args is None:
            continue
        referenced = _named_types(func.parameters, structs, classes)
        imported = ", ".join([func.name, *referenced])
        lines.append(f"def test_{func.name}_importable():")
        lines.append(f"    from {package_name} import {imported}")
        lines.append("")
        lines.append(f"    {func.name}({args})")
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"
