# Generated by native2py. Do not edit by hand — re-run `native2py generate`.
from ._native import petro_api as _native

pvt_set_fluid = _native.petro_api.pvt_set_fluid
solution_gor = _native.petro_api.solution_gor
oil_fvf = _native.petro_api.oil_fvf
oil_viscosity = _native.petro_api.oil_viscosity
gas_z_factor = _native.petro_api.gas_z_factor
bubble_point = _native.petro_api.bubble_point
pvt_state = _native.petro_api.pvt_state
tubing_bhp = _native.petro_api.tubing_bhp
vogel_rate = _native.petro_api.vogel_rate
last_error = _native.petro_api.last_error

__all__ = ["pvt_set_fluid", "solution_gor", "oil_fvf", "oil_viscosity", "gas_z_factor", "bubble_point", "pvt_state", "tubing_bhp", "vogel_rate", "last_error"]
