# Generated by nativegate. Do not edit by hand — re-run `ngate generate`.
"""MCP server exposing this service's endpoints as tools for an LLM client.

Not a second implementation of anything: FastMCP derives one tool per route
from the router's OpenAPI schema, so the tool surface and the HTTP surface are
the same routes and cannot drift. Tool names are the routes' `operation_id`
(the service name plus the native symbol name, so ids stay unique when several
services are composed) and tool descriptions are the endpoints' docstrings.

The native call still runs under router.py's `_NATIVE_LOCK`: a tool call
re-enters the same endpoint function in the same process, so MCP does NOT open
a second, unsynchronised path into COMMON-block state.
"""
from fastapi import FastAPI
from fastmcp import FastMCP

from .router import router

# Deliberately bare — the router and nothing else. `FastMCP.from_fastapi` calls
# this app back over an in-process ASGI transport for every tool invocation, so
# installing auth middleware HERE would mean the server authenticating to
# itself with a credential hardcoded in generated source. Auth belongs on the
# outer app that mounts `mcp_app`, where it already guards the REST routes.
_inner = FastAPI(title="petro_api")
_inner.include_router(router)

mcp = FastMCP.from_fastapi(app=_inner, name="petro_api")

# path="/" because the app that mounts this does so at "/mcp", and FastMCP's
# own default path is ALSO "/mcp" — passing neither serves the endpoint at
# "/mcp/mcp". The app mounting this MUST take `lifespan=mcp_app.lifespan`:
# FastMCP's session manager starts there, and without it every tool call fails
# at runtime with "task group was not initialized".
mcp_app = mcp.http_app(path="/")
