# Generated by nativegate. Do not edit by hand — re-run `ngate generate`.
"""Request identity, access logging, authentication and limits for petro_api.

Installed by both `service.py` and the gateway app via `install_middleware`.
See the nativegate docs on production readiness for what each layer does and,
just as importantly, what it does not.
"""
from __future__ import annotations

import hmac
import logging
import os
import signal
import time
import uuid
from collections import deque
from threading import Lock

from fastapi import HTTPException, Request
from fastapi.responses import JSONResponse

__all__ = [
    "install_middleware",
    "readiness",
    "start_draining",
    "AuthNotConfigured",
    "current_request_id",
]

_LOG = logging.getLogger("nativegate.petro_api")
_ACCESS_LOG = logging.getLogger("nativegate.petro_api.access")

# Baked in at generate time from `api.auth` in nativegate.yaml. Deliberately not
# an environment variable: a service generated to require authentication must
# not be silently downgraded by the environment it happens to start in.
AUTH_MODE = "none"

# Paths that never require authentication. An orchestrator probing readiness
# has no credentials, and a liveness probe that 401s is a service that looks
# dead and gets restarted forever.
_UNAUTHENTICATED_PATHS = frozenset({"/healthz", "/readyz"})


class AuthNotConfigured(RuntimeError):
    """Raised at startup when auth is required but no keys are present."""


def _load_api_keys() -> list[str]:
    raw = os.environ.get("NATIVEGATE_API_KEYS", "")
    return [k.strip() for k in raw.split(",") if k.strip()]


def _int_env(name: str, default: int) -> int:
    try:
        return int(os.environ.get(name, "") or default)
    except ValueError:
        _LOG.warning("%s is not an integer; falling back to %s", name, default)
        return default


class _RateLimiter:
    """Per-process sliding window. See the module docstring for the caveat.

    A deque of timestamps per client rather than a token bucket: the window is
    exact, and for the request rates a native-compute service sees the memory
    is irrelevant. Old entries are evicted on access, so an idle client's
    deque costs nothing after its window passes.
    """

    def __init__(self, per_minute: int) -> None:
        self.per_minute = per_minute
        self._hits: dict[str, deque[float]] = {}
        self._lock = Lock()

    def allow(self, client: str, now: float) -> bool:
        if self.per_minute <= 0:
            return True
        cutoff = now - 60.0
        with self._lock:
            hits = self._hits.setdefault(client, deque())
            while hits and hits[0] < cutoff:
                hits.popleft()
            if not hits:
                # Keeps the dict from growing without bound as clients churn.
                self._hits.pop(client, None)
                hits = self._hits.setdefault(client, deque())
            if len(hits) >= self.per_minute:
                return False
            hits.append(now)
            return True


def current_request_id(request: Request) -> str:
    """The id for this request, for handlers that want to log against it."""
    return getattr(request.state, "request_id", "-")


def install_middleware(app, service_name: str = "petro_api") -> None:
    """Attach every middleware layer to `app`, outermost first.

    Order matters and is not arbitrary:

    1. request id — so everything below it, including rejections, can be
       correlated. A 401 with no id is an unanswerable support ticket.
    2. body size — cheapest rejection, and it runs before anything reads the
       body into memory.
    3. auth — before the rate limiter, so an unauthenticated flood is rejected
       without consuming the caller's quota, and so the limiter can key on the
       authenticated identity rather than a spoofable address.
    4. rate limit — keyed by API key when there is one, client address if not.
    5. access log — innermost of the cross-cutting layers, so its duration
       measurement covers the handler and not the middleware above it.

    Starlette runs `add_middleware` in reverse registration order, so these
    are registered bottom-up.
    """
    api_keys = _load_api_keys()
    if AUTH_MODE == "api_key" and not api_keys:
        raise AuthNotConfigured(
            f"{service_name} is configured with `api.auth: api_key` but "
            "NATIVEGATE_API_KEYS is empty. Refusing to start rather than serve "
            "unauthenticated. Set it to a comma-separated list of keys, or "
            "regenerate the service with `api.auth: none` if it is genuinely "
            "meant to be open."
        )
    if AUTH_MODE == "none":
        # Not a warning on every request — once, at startup, where an operator
        # reading boot logs will actually see it.
        _LOG.warning(
            "%s is serving WITHOUT authentication (api.auth: none). Anything "
            "that can reach the port can call the native code.", service_name
        )

    limiter = _RateLimiter(_int_env("NATIVEGATE_RATE_LIMIT_PER_MINUTE", 0))
    max_body = _int_env("NATIVEGATE_MAX_REQUEST_BYTES", 1_048_576)

    @app.middleware("http")
    async def _access_log(request: Request, call_next):
        started = time.perf_counter()
        response = await call_next(request)
        duration_ms = (time.perf_counter() - started) * 1000.0
        # Structured via `extra` so a JSON formatter can pick the fields up,
        # while the default formatter still prints something readable.
        _ACCESS_LOG.info(
            "%s %s %s %.1fms",
            request.method, request.url.path, response.status_code, duration_ms,
            extra={
                "request_id": current_request_id(request),
                "method": request.method,
                "path": request.url.path,
                "status": response.status_code,
                "duration_ms": round(duration_ms, 3),
                "service": service_name,
            },
        )
        response.headers["X-Response-Time-Ms"] = f"{duration_ms:.1f}"
        return response

    @app.middleware("http")
    async def _rate_limit(request: Request, call_next):
        if limiter.per_minute > 0 and request.url.path not in _UNAUTHENTICATED_PATHS:
            client = getattr(request.state, "auth_key", None) or (
                request.client.host if request.client else "unknown"
            )
            if not limiter.allow(client, time.monotonic()):
                _LOG.warning(
                    "rate limit exceeded for %s on %s (request %s)",
                    client, request.url.path, current_request_id(request),
                )
                return JSONResponse(
                    status_code=429,
                    content={
                        "error": "rate limit exceeded",
                        "limit_per_minute": limiter.per_minute,
                        "request_id": current_request_id(request),
                    },
                    headers={"Retry-After": "60"},
                )
        return await call_next(request)

    @app.middleware("http")
    async def _authenticate(request: Request, call_next):
        if AUTH_MODE == "api_key" and request.url.path not in _UNAUTHENTICATED_PATHS:
            presented = request.headers.get("x-api-key") or ""
            bearer = request.headers.get("authorization", "")
            if not presented and bearer.lower().startswith("bearer "):
                presented = bearer[7:].strip()
            # compare_digest against every key: a short-circuit `in` leaks key
            # length and position through timing. The loop is deliberately not
            # broken early for the same reason.
            matched = False
            for key in api_keys:
                if hmac.compare_digest(presented, key):
                    matched = True
            if not matched:
                _LOG.warning(
                    "rejected unauthenticated %s %s (request %s)",
                    request.method, request.url.path, current_request_id(request),
                )
                return JSONResponse(
                    status_code=401,
                    content={
                        "error": "unauthorized",
                        "request_id": current_request_id(request),
                    },
                    headers={"WWW-Authenticate": "Bearer"},
                )
            request.state.auth_key = presented
        return await call_next(request)

    @app.middleware("http")
    async def _limit_body(request: Request, call_next):
        declared = request.headers.get("content-length")
        if declared is not None:
            try:
                if int(declared) > max_body:
                    return JSONResponse(
                        status_code=413,
                        content={
                            "error": "request body too large",
                            "max_request_bytes": max_body,
                            "request_id": current_request_id(request),
                        },
                    )
            except ValueError:
                return JSONResponse(
                    status_code=400,
                    content={"error": "malformed Content-Length"},
                )
        return await call_next(request)

    @app.middleware("http")
    async def _request_id(request: Request, call_next):
        # Honour an inbound id so a trace survives the hop from a gateway or
        # service mesh, but bound its length and character set: it is attacker
        # -controlled and it ends up in log lines.
        inbound = request.headers.get("x-request-id", "")
        if inbound and len(inbound) <= 64 and inbound.isascii() and inbound.isprintable():
            request_id = inbound
        else:
            request_id = uuid.uuid4().hex[:12]
        request.state.request_id = request_id
        response = await call_next(request)
        response.headers["X-Request-ID"] = request_id
        return response


_DRAINING = False


def start_draining() -> None:
    """Stop reporting ready. Called on SIGTERM; safe to call directly."""
    global _DRAINING
    _DRAINING = True
    _LOG.info("draining: /readyz will report 503 while in-flight work finishes")


def readiness(app, service_name: str = "petro_api"):
    """Register `/readyz`, distinct from `/healthz` liveness.

    WHAT READINESS IS ACTUALLY FOR HERE

    The obvious reading — "has the app finished starting?" — is worth nothing
    in this service. `service.py` imports `router.py`, which imports the native
    extension at module scope, so a worker that failed to load it never becomes
    able to answer anything at all. Any request that gets a response at all is
    proof the extension imported. A readiness probe asserting that would be a
    slower liveness probe.

    What readiness genuinely buys is **draining**. On a rolling deploy or a
    scale-down, the orchestrator sends SIGTERM and gunicorn stops accepting new
    work while finishing what is in flight. Without a readiness signal the load
    balancer keeps routing to that worker for as long as its own health check
    interval, and those requests are refused. Reporting 503 the moment SIGTERM
    lands takes the process out of rotation *before* it stops accepting, which
    is the difference between a clean deploy and a burst of 502s.

    Liveness must NOT do this: a draining process is deliberately not ready but
    perfectly alive, and a liveness probe that failed here would get it killed
    mid-request instead of drained.
    """

    # Chained, not replaced. gunicorn and uvicorn install their own SIGTERM
    # handlers to run graceful shutdown; overwriting one would turn a graceful
    # drain into an abrupt exit, which is the opposite of the goal.
    try:
        previous = signal.getsignal(signal.SIGTERM)

        def _drain_then_delegate(signum, frame):
            start_draining()
            if callable(previous):
                previous(signum, frame)

        signal.signal(signal.SIGTERM, _drain_then_delegate)
    except (ValueError, OSError):
        # Not the main thread (some test runners, some embeddings). Draining is
        # an optimisation, not a correctness requirement — carry on without it.
        _LOG.debug("could not install a SIGTERM drain handler; /readyz is static")

    @app.get("/readyz", tags=["health"])
    def readyz():
        if _DRAINING:
            raise HTTPException(status_code=503, detail="draining")
        return {"status": "ready", "service": service_name}

    return readyz
