# Generated by nativegate. Do not edit by hand — re-run `ngate generate`.
import os
import threading
from typing import Annotated
import numpy as np
from fastapi import APIRouter, HTTPException
from pydantic import Field

from . import pvt_set_fluid, solution_gor, oil_fvf, oil_viscosity, gas_z_factor, bubble_point, pvt_state, tubing_bhp, vogel_rate, last_error

# Maximum number of elements accepted in any array argument of any endpoint.
#
# PLACEHOLDER. nativegate does not yet know the real extent of a native array
# argument — the IR records that a parameter IS an array, not how long the
# routine expects it to be. Recovering the declared extent needs the fparser2
# front end (ROADMAP 1.4); until then one configurable cap stands in for all
# of them, so an unbounded request body cannot exhaust this worker's memory.
# Pydantic rejects an oversized list during request validation, so the caller
# gets a 422 and the array is never materialised for the native call.
#
# Raise it for a service with genuinely large inputs; do not remove it.
MAX_ARRAY_ITEMS = int(os.environ.get("NATIVEGATE_MAX_ARRAY_ITEMS", "65536"))

# Every native call below is serialised through this one process-wide lock.
#
# Fortran COMMON blocks are process-global storage, not per-call state. A
# routine like PVTINI writes COMMON /FLUID/ and a later call to PVTRS,
# PVTBO or PVTVIS reads it back — the header's own contract is "CALL
# PVTSET(P) THEN USE THE COMMON". FastAPI runs synchronous `def` endpoints
# in a threadpool, so without this lock two requests configuring different
# fluids interleave their writes and reads in the SAME COMMON block and
# each caller gets numbers computed from the other caller's fluid. Nothing
# raises, nothing logs; the answers are just wrong.
#
# Per-request objects cannot fix this the way they fix a stateful C++ class:
# COMMON is reachable from every instance because it belongs to the process.
#
# DO NOT REMOVE THIS TO IMPROVE THROUGHPUT. It caps native execution at one
# concurrent call per process on purpose. The supported ways to go faster are
# more processes, or an API reshaped so a configure+read pair is one call.
#
# RLock, not Lock: if one generated endpoint is ever changed to call another,
# a plain Lock would deadlock the request against itself.
_NATIVE_LOCK = threading.RLock()

router = APIRouter(tags=["petro_api"])

# Symbols this build recognised and refused to bind, with the reason.
#
# Refusal is nativegate's safety mechanism (a non-const char* output buffer
# has no length; a pointer return has no ownership; a derived-type Fortran
# result has no mapping), so the refusals are part of this service's
# contract and not an implementation detail. An EMPTY mapping means this
# build refused nothing; a 404 on this route means the service predates
# the feature and cannot tell you either way.
_UNEXPOSED: dict[str, str] = {
}

@router.get("/_unexposed", tags=["introspection"], operation_id="petro_api_unexposed")
def _nativegate_unexposed() -> dict[str, str]:
    """Symbols the parser recognised but refused to bind, and why."""
    return _UNEXPOSED

@router.post("/pvt_set_fluid", operation_id="petro_api_pvt_set_fluid")
def pvt_set_fluid_endpoint(api_gravity: float, gas_gravity: float, temp_f: float, icorr: int):
    """Call the native subroutine `pvt_set_fluid`."""
    with _NATIVE_LOCK:
        pvt_set_fluid(api_gravity, gas_gravity, temp_f, icorr)
    return {"ok": True}

@router.post("/solution_gor", operation_id="petro_api_solution_gor")
def solution_gor_endpoint(pressure: float):
    """Call the native routine `solution_gor`."""
    with _NATIVE_LOCK:
        result = solution_gor(pressure)
    return {"result": result}

@router.post("/oil_fvf", operation_id="petro_api_oil_fvf")
def oil_fvf_endpoint(pressure: float):
    """Call the native routine `oil_fvf`."""
    with _NATIVE_LOCK:
        result = oil_fvf(pressure)
    return {"result": result}

@router.post("/oil_viscosity", operation_id="petro_api_oil_viscosity")
def oil_viscosity_endpoint(pressure: float):
    """Call the native routine `oil_viscosity`."""
    with _NATIVE_LOCK:
        result = oil_viscosity(pressure)
    return {"result": result}

@router.post("/gas_z_factor", operation_id="petro_api_gas_z_factor")
def gas_z_factor_endpoint(pressure: float):
    """Call the native routine `gas_z_factor`."""
    with _NATIVE_LOCK:
        result = gas_z_factor(pressure)
    return {"result": result}

@router.post("/bubble_point", operation_id="petro_api_bubble_point")
def bubble_point_endpoint(target_gor: float):
    """Call the native routine `bubble_point`."""
    with _NATIVE_LOCK:
        result = bubble_point(target_gor)
    return {"result": result}

@router.post("/pvt_state", operation_id="petro_api_pvt_state")
def pvt_state_endpoint(pressure: float, n: int, props: Annotated[list[float], Field(max_length=MAX_ARRAY_ITEMS)]):
    """Call the native subroutine `pvt_state`."""
    if n != len(props):
        raise HTTPException(
            status_code=422,
            detail=f"n ({n}) must equal len(props) ({len(props)}): the native routine uses n as the extent of props and would index past the end of the buffer.",
        )
    props = np.array(props, dtype=np.float64)
    with _NATIVE_LOCK:
        props = pvt_state(pressure, props, n)
    return {"props": props.tolist()}

@router.post("/tubing_bhp", operation_id="petro_api_tubing_bhp")
def tubing_bhp_endpoint(wellhead_p: float, q_oil: float, q_water: float, q_gas: float, diameter: float, roughness: float, tvd: float, md: float, nseg: int):
    """Call the native routine `tubing_bhp`."""
    with _NATIVE_LOCK:
        result = tubing_bhp(wellhead_p, q_oil, q_water, q_gas, diameter, roughness, tvd, md, nseg)
    return {"result": result}

@router.post("/vogel_rate", operation_id="petro_api_vogel_rate")
def vogel_rate_endpoint(res_pressure: float, flowing_bhp: float, q_max: float):
    """Call the native routine `vogel_rate`."""
    with _NATIVE_LOCK:
        result = vogel_rate(res_pressure, flowing_bhp, q_max)
    return {"result": result}

@router.post("/last_error", operation_id="petro_api_last_error")
def last_error_endpoint():
    """Call the native routine `last_error`."""
    with _NATIVE_LOCK:
        result = last_error()
    return {"result": result}
