# Generated by native2py. Do not edit by hand — re-run `native2py generate`.
import threading
import numpy as np
from fastapi import APIRouter

from . import pvt_set_fluid, solution_gor, oil_fvf, oil_viscosity, gas_z_factor, bubble_point, pvt_state, tubing_bhp, vogel_rate, last_error

# Every native call below is serialised through this one process-wide lock.
#
# Fortran COMMON blocks are process-global storage, not per-call state. A
# routine like PVTINI writes COMMON /FLUID/ and a later call to PVTRS,
# PVTBO or PVTVIS reads it back — the header's own contract is "CALL
# PVTSET(P) THEN USE THE COMMON". FastAPI runs synchronous `def` endpoints
# in a threadpool, so without this lock two requests configuring different
# fluids interleave their writes and reads in the SAME COMMON block and
# each caller gets numbers computed from the other caller's fluid. Nothing
# raises, nothing logs; the answers are just wrong.
#
# Per-request objects cannot fix this the way they fix a stateful C++ class:
# COMMON is reachable from every instance because it belongs to the process.
#
# DO NOT REMOVE THIS TO IMPROVE THROUGHPUT. It caps native execution at one
# concurrent call per process on purpose. The supported ways to go faster are
# more processes, or an API reshaped so a configure+read pair is one call.
#
# RLock, not Lock: if one generated endpoint is ever changed to call another,
# a plain Lock would deadlock the request against itself.
_NATIVE_LOCK = threading.RLock()

router = APIRouter(tags=["petro_api"])

@router.post("/pvt_set_fluid")
def pvt_set_fluid_endpoint(api_gravity: float, gas_gravity: float, temp_f: float, icorr: int):
    with _NATIVE_LOCK:
        pvt_set_fluid(api_gravity, gas_gravity, temp_f, icorr)
    return {"ok": True}

@router.post("/solution_gor")
def solution_gor_endpoint(pressure: float):
    with _NATIVE_LOCK:
        result = solution_gor(pressure)
    return {"result": result}

@router.post("/oil_fvf")
def oil_fvf_endpoint(pressure: float):
    with _NATIVE_LOCK:
        result = oil_fvf(pressure)
    return {"result": result}

@router.post("/oil_viscosity")
def oil_viscosity_endpoint(pressure: float):
    with _NATIVE_LOCK:
        result = oil_viscosity(pressure)
    return {"result": result}

@router.post("/gas_z_factor")
def gas_z_factor_endpoint(pressure: float):
    with _NATIVE_LOCK:
        result = gas_z_factor(pressure)
    return {"result": result}

@router.post("/bubble_point")
def bubble_point_endpoint(target_gor: float):
    with _NATIVE_LOCK:
        result = bubble_point(target_gor)
    return {"result": result}

@router.post("/pvt_state")
def pvt_state_endpoint(pressure: float, n: int, props: list[float]):
    props = np.array(props, dtype=np.float64)
    with _NATIVE_LOCK:
        props = pvt_state(pressure, props, n)
    return {"props": props.tolist()}

@router.post("/tubing_bhp")
def tubing_bhp_endpoint(wellhead_p: float, q_oil: float, q_water: float, q_gas: float, diameter: float, roughness: float, tvd: float, md: float, nseg: int):
    with _NATIVE_LOCK:
        result = tubing_bhp(wellhead_p, q_oil, q_water, q_gas, diameter, roughness, tvd, md, nseg)
    return {"result": result}

@router.post("/vogel_rate")
def vogel_rate_endpoint(res_pressure: float, flowing_bhp: float, q_max: float):
    with _NATIVE_LOCK:
        result = vogel_rate(res_pressure, flowing_bhp, q_max)
    return {"result": result}

@router.post("/last_error")
def last_error_endpoint():
    with _NATIVE_LOCK:
        result = last_error()
    return {"result": result}
