# Generated by native2py. Do not edit by hand — re-run `native2py generate`.
import numpy as np
from fastapi import APIRouter

from . import pvt_set_fluid, solution_gor, oil_fvf, oil_viscosity, gas_z_factor, bubble_point, pvt_state, tubing_bhp, vogel_rate, last_error

router = APIRouter(tags=["petro_api"])

@router.post("/pvt_set_fluid")
def pvt_set_fluid_endpoint(api_gravity: float, gas_gravity: float, temp_f: float, icorr: int):
    pvt_set_fluid(api_gravity, gas_gravity, temp_f, icorr)
    return {"ok": True}

@router.post("/solution_gor")
def solution_gor_endpoint(pressure: float):
    return {"result": solution_gor(pressure)}

@router.post("/oil_fvf")
def oil_fvf_endpoint(pressure: float):
    return {"result": oil_fvf(pressure)}

@router.post("/oil_viscosity")
def oil_viscosity_endpoint(pressure: float):
    return {"result": oil_viscosity(pressure)}

@router.post("/gas_z_factor")
def gas_z_factor_endpoint(pressure: float):
    return {"result": gas_z_factor(pressure)}

@router.post("/bubble_point")
def bubble_point_endpoint(target_gor: float):
    return {"result": bubble_point(target_gor)}

@router.post("/pvt_state")
def pvt_state_endpoint(pressure: float, n: int, props: list[float]):
    props = np.array(props, dtype=np.float64)
    props = pvt_state(pressure, props, n)
    return {"props": props.tolist()}

@router.post("/tubing_bhp")
def tubing_bhp_endpoint(wellhead_p: float, q_oil: float, q_water: float, q_gas: float, diameter: float, &
                        roughness: float, tvd: float, md: float, nseg: int):
    return {"result": tubing_bhp(wellhead_p, q_oil, q_water, q_gas, diameter, &
                        roughness, tvd, md, nseg)}

@router.post("/vogel_rate")
def vogel_rate_endpoint(res_pressure: float, flowing_bhp: float, q_max: float):
    return {"result": vogel_rate(res_pressure, flowing_bhp, q_max)}

@router.post("/last_error")
def last_error_endpoint():
    return {"result": last_error()}
