# Generated by native2py. Do not edit by hand — re-run `native2py generate`.
from fastapi import FastAPI

from .router import router

app = FastAPI(title="petro_api")
app.include_router(router)


@app.get("/healthz", tags=["health"])
def healthz():
    """Liveness: the process is up and the native extension imported."""
    return {"status": "ok", "service": "petro_api"}
