# Generated by native2py. Do not edit by hand — re-run `native2py generate`.
import logging
import os
import uuid

from fastapi.responses import JSONResponse
from fastapi import FastAPI, Request

from .router import router

app = FastAPI(title="petro_api")
app.include_router(router)


@app.get("/healthz", tags=["health"])
def healthz():
    """Liveness: the process is up and the native extension imported."""
    return {"status": "ok", "service": "petro_api"}


_LOG = logging.getLogger("native2py.petro_api")

# Off by default. A native routine's exception text can carry deck values,
# array contents or absolute paths from the build machine; none of that should
# leave the process just because something failed. Turn it on deliberately,
# in a non-production environment, when a caller needs to see why.
_DEBUG_ERRORS = os.environ.get("NATIVE2PY_DEBUG_ERRORS", "").lower() not in ("", "0", "false", "no")


@app.exception_handler(Exception)
async def _unhandled_native_error(request: Request, exc: Exception):
    """Give a failed request a JSON body and an id that matches the log line.

    Without this, Starlette answers `Internal Server Error` as plain text —
    safe, but untraceable and a second content type for clients to parse.

    HTTPException does NOT reach here — FastAPI handles it first — so the
    generated argument-validation errors keep their own status and detail.

    Caveats, both real: with `debug=True` Starlette returns its traceback
    response *instead* of this one, so do not enable debug on a deployed
    service; and a segfault, Fortran STOP or hang kills the worker process
    before any Python handler runs. See docs/production-readiness.md.
    """
    error_id = uuid.uuid4().hex[:12]
    # .exception() so the traceback reaches the log exactly once, keyed by the
    # same id the caller was given — that pairing is the whole point.
    _LOG.exception(
        "unhandled error %s on %s %s", error_id, request.method, request.url.path
    )
    body = {"error": "internal server error", "error_id": error_id}
    if _DEBUG_ERRORS:
        body["detail"] = f"{type(exc).__name__}: {exc}"
    return JSONResponse(status_code=500, content=body)
